### ISSUE TITLE
Fibonacci everywhere

### ISSUE THREAD

**Issue by Franx0** [madridjs/talks#1]
Propongo una charla introductoria de Javascript en la que se explicará la sucesión de Fibonacci de manera sencilla. 
Para ello propongo realizar un ejercicio en el que se cree y ejecute un código capaz de generar la sucesión de Fibonacci utilizando diferentes bucles e incluso funciones recursivas.
Considero que es un buen ejercicio introductorio en el que además se revisarán conceptos como array, bucle, condición, función, variable, contador, el comportamiento de Javascript para contar elementos, etc.

Mi nombre es Fran, tengo 25 años, estoy empezando en esto de la programación pero he descubierto que me encanta. Me he formado en la escuela Ironhack de Madrid y soy un culo inquieto, siempre intentando hacer cosas nuevas y diferentes.
Me encanta el mundo de la música y además aporreo la guitarra (en mi casa todos sordos ¬¬)
Podéis conocer un poco más de mí en el siguiente enlace:
http://write2learn.herokuapp.com/

Saludetes compañeros ;)

**Comment by lucascepeda** [comment]
:+1:

**Comment by alexfernandez** [comment]
¡Buenas, Fran! En febrero ya tenemos charla, ¿te viene bien hacerla a finales de marzo?

**Comment by Serabe** [comment]
Sería interesante que en el caso de usar funciones recursivas se hiciese una que se pudiera optimizar (usando tail call optimization) ya que ES6/ES2015/ES${ponga el nombre que le dé la gana} introduce TCO.

**Comment by Franx0** [comment]
Yo soy un 'mandao' Alex, dime fecha exacta y me preparo unas slides guapas guapas! En principio no tengo problema con que sea a finales de Marzo =)

**Comment by alexfernandez** [comment]
Vale, en principio queda a finales de marzo, te avisaremos con varias semanas de antelación.

**Comment by Franx0** [comment]
Perfecto =)

**Comment by alexfernandez** [comment]
@Franx0, ¿puedes el jueves 26 de marzo?
