### ISSUE TITLE
Magia Modular

### ISSUE THREAD

**Issue by manolomaldonado** [madridjs/talks#10]
Modularizando nuestra aplicación backbone siguiendo CommonJS con browserify. 
Hoy en día se pueden ver muchos artículos en blogs de de como crear módulos en nuestro javascript. Para tener aplicaciones en producción son importantes de cara a encapsular el código, mantener unidades de código separado y ordenado. También simular propiedades y métodos privados.

Los tutoriales y guías tienen un claro protagonista: Require.js. Pero  no todo es AMD. Veremos como hemos optado por utilizar el standard de node.js para modularizar una aplicación real utilizando para ello la magia de browserify, viendo herramientas disponibles para ello como watchify o configurar browserify en nuestro gulp y algunos tips and tricks adaptando algunos plugins de jQuery con UMD.

David Rielo, es desarrollador respondable de frontend en Lextrend (http://www.lextrend.com) donde trabaja principalmente con Backbone, Node y Gulp. Comenzó el lado servidor con Java en sus inicios pero rapidaménte se vió atraido por el desarrollo del lado cliente y por las posibilidades de javascript donde descubrió su verdadera vocación.

**Comment by alexfernandez** [comment]
¿Otra charla avanzada?

**Comment by manolomaldonado** [comment]
Hola Alex, esta charla si es algo más avanzada. Si crees conveniente encajarla en otro momento por nuestra parte no hay inconveniente.

**Comment by alexfernandez** [comment]
Ésta ya quedaría para septiembre, a no ser que nos falle alguna.

**Comment by alexfernandez** [comment]
Manolo, esta charla lleva aquí un montón de tiempo, ¿la cerramos, o sigues dispuesto a darla?
