### ISSUE TITLE
Decoupling the CMS with React and CouchDB

### ISSUE THREAD

**Issue by juampynr** [madridjs/talks#11]
¡Saludos!

La semana pasada di esta charla en la DrupalCamp Spain. Trata de cómo hemos desacoplado el front de Drupal exportando el contenido a CouchDB y consumiéndolo en una aplicación web isomórfica con NodeJS y React.

Se trata de la web de la empresa en la que trabajo, [Lullabot](https://www.lullabot.com). Lanzaremos la nueva versión en unos días.

Aquí tenéis la [descripción de la charla](http://2015.drupalcamp.es/en/node/70) más [las diapositivas](http://juampy72.github.io/decoupling-cms-react-couchdb). En unos días habrá disponible una grabación de la misma.

Tengo esta charla preparada en inglés pero si lo preferís lo puedo hacer en español.

## Sobre mí

Soy [Juampy NR](http://about.me/juampy), programador back end en [Lullabot](https://www.lullabot.com), una empresa distribuida de estrategia, diseño y desarrollo. Participo activamente en la comunidad de Drupal tanto en [módulos como en el core](https://www.drupal.org/u/juampy) y he escrito dos [libros sobre Drush](http://www.amazon.com/Drush-Developers-Juampy-Novillo-Requena-ebook/dp/B00SYOBXYG), la interfaz de línea de comandos para Drupal. En los últimos tres años he descubierto mi lugar en el mundo de JavaScript gracias a tecnologías como AngularJS y React; disfrutando la experiencia y escribiendo [artículos](https://www.lullabot.com/blog/article/processing-forms-angularjs).

**Comment by alexfernandez** [comment]
Descripción, copiada del enlace:

Last year, Mateu and I shared the goodies of decoupling bits of Drupal's front end. This time we will see how we are fully decocupling Lullabot.com using React and CouchDB.

React is a JavaScript library created by Facebook. It's code can run both in the server and the client and is structured in simple and reusable components.

CouchDB is a no-SQL database engine widely used in the NodeJS community. It has a built in REST API and its queries are written in JavaScript.

This will be a technical session where we will see the main challenges that we faced in the project. The main topics will be:

    How content flows from the back end to the front end.
    Back end architecture.
    Front end architecture.
    How React renders an article.
    Forms in React and NodeJS.
    What is an isomorphic request.

Nivel intermedio pone, ¿la ves más de iniciación o avanzada? Yo diría que avanzada, pero tú eres el experto :)

En principio ya queda para el curso que viene, te avisaremos con varias semanas de antelación para que tengas tiempo de sobra. ¡Gracias!

**Comment by juampy72** [comment]
@alexfernandez, sí, yo creo que es avanzada.

**Comment by alexfernandez** [comment]
Buenas, volvemos a la carga después de las vacaciones. ¿Estarías disponible para dar esta charla en marzo?

**Comment by juampynr** [comment]
¡Hola Alex!

Claro. De momento, los únicos días que no puedo en marzo son el 24 y el 25.

**Comment by alexfernandez** [comment]
Ouch! El 24 es el día que estábamos pensando: https://github.com/madridjs/talks/issues/14#issuecomment-171219114  Igual podemos hacerlo el 23?

**Comment by juampynr** [comment]
Vale por mí.

**Comment by juampynr** [comment]
¡Hola @alexfernandez!

Llevo unos meses centrado en PHP y me he descolgado un poco del tema de la charla. Ha pasado mucho tiempo desde que la propuse y ahora no creo que pueda hacer algo tan interesante.

¿Tienes alternativas para ese día? Si vuelvo a meterme en el proyecto, la volveré a proponer.

**Comment by alexfernandez** [comment]
No hay problema, cerramos el issue y lo reabres cuando te apetezca.

**Comment by juampynr** [comment]
¡Gracias!
