### ISSUE TITLE
Augur Project

### ISSUE THREAD

**Issue by pqdeep** [madridjs/talks#12]
Hello, I'm with the Augur Project (augur.net) which is launching the world's first open-source, global prediction market platfom. The system relies heavily on js (reactJS to be specific) and we're interested in presenting the concept and getting feedback from your group. My email: perry@augur.net. Thank you very much for your time

Hola, soy con el Proyecto Augur (augur.net) que se lanzará el primero platforma global de mercados de predicciónes. El sistema se basa en gran medida en js (reactJS specíficamente) y estamos interesados en presentarlo el concepto y conocer la opinión de su grupo. Si hay interés, nos gustaria hacer un presentacion en Septiembre - idealmente entre 14 - 19 de Septiembre. Muchas gracias para su tiempo.

**Comment by alexfernandez** [comment]
It looks very interesting! We work on a FIFO basis and we already have talks for September and October, so yours might go for November, but if there are cancellations your presentation might be scheduled sooner. Let me know if this is OK with you.

One thing: do you see your talk as introductory or as advanced?

**Comment by pqdeep** [comment]
September would be ideal (ideally in the September week of 14-19), but fine with being scheduled tenatively for November. Talk could be both - brief introductory of concept then a Q&A Skype with our lead developers to take detailed tech questions about the system. An info packet (or simply links to the codebase) could be sent as orientation in advance to save more time for detailed Q&A.

**Comment by alexfernandez** [comment]
Ah, so it's all Skype, or just the Q&A session? If it's presential, would you have to come from abroad for the talk?

**Comment by pqdeep** [comment]
Just the Q&A session and depending on how schedules look, slight possibility that might be live as well. Depends on how things look in November.

**Comment by alexfernandez** [comment]
Perfect! We will let you know with at least a month in advance, or more if you need to book flights or whatever. Looking forward to your presentation!

**Comment by alexfernandez** [comment]
Event published: http://www.meetup.com/es/madridjs/events/225520079/?eventId=225520079.
