### ISSUE TITLE
Componentizando la web con la ayuda de Polymer

### ISSUE THREAD

**Issue by jorgecasar** [madridjs/talks#13]
# Descripción
Polymer es una librería que ayuda a los desarrolladores a crear fácilmente sitios maravillosos y reusables webcomponents para la web moderna. Hace casi 4 meses salió la versión 1.0, estable y lista para producción.

En la charla veremos qué es un web component, cómo empezar a desarrollar uno, el ciclo de vida, el data binding, los behaviors (alternativa a la herencia), depende como vayamos de tiempo también podríamos hablar de testing unitario y distribución empaquetado para producción.

# Bio de ponente
Desde 2009 he dedicado mi tiempo a escribir código javascript. También soy ponente en horas de siesta, mis charlas suelen ser después de comer para evitar que la gente duerma durante la conferencia. Fui BlackBerry Developer Evangelist y aprendí mucho sobre aplicaciones móviles, no solo desde el punto de vista del desarrollo, también de negocio. Espero que podamos hablar y compartir conversaciones interesantes y algunos trozos de código. Desde 2003 que empecé con el desarrollo web, he trabajado en empresas con webs de alto rendimiento como Softonic.com y he participado en proyectos piloto en HTML5 para diferentes compañías. Desde hace 4 meses trabajo en un proyecto basado en webcomponents usando Polymer. Y en los últimos años he querido compartir el conocimiento adquirido dando charlas, talleres y formación en diferentes foros como Microsoft Webcamps, Campus Party, Salón MiEmpresa, AECOMO Academy, JavaScriptIO, Escuela IT, etc...

**Comment by alexfernandez** [comment]
La programamos como introductoria para el jueves 24 de septiembre. Los asuntos opcionales (testing, distribución) los podemos dejar para una charla avanzada más adelante, si te parece.

**Comment by jorgecasar** [comment]
Perfecto!

--



*Jorge del Casarjorgedelcasar.es <http://jorgedelcasar.es/>+Jorge del Casar
<https://plus.google.com/101957952424598424873/>@jorgecasar
<http://www.twitter.com/jorgecasar>*

El 10 de septiembre de 2015, 10:03, Alex Fernández <notifications@github.com

**Comment by alexfernandez** [comment]
Esta charla lleva tiempo abierta, la cierro y si sigues dispuesto a darla reabre con confianza.
