### ISSUE TITLE
Mapas con vitaminas

### ISSUE THREAD

**Issue by hhkaos** [madridjs/talks#14]
## Descripción

Cada vez nos encontramos más aplicaciones que utilizan los mapas con distintos propósitos
* Gamificar: [LevelUp](https://www.thelevelup.com/), [quizzity](http://david-peter.de/quizzity/), [MapQuiz](http://maps.esri.com/rc/quiz/index.html), [Swarm](https://www.swarmapp.com/)
* Realizar análisis espacial: [calcular tiempos de conducción](http://developers.arcgis.com/javascript/samples/routetask_multiple_servicesarea/), [realizar operaciones espaciales](http://output.jsbin.com/hecize/1), [planificar rutas](http://developers.arcgis.com/javascript/samples/routetask_multiple_stops/),  [Big Data Analytics](http://coolmaps.esri.com/#8), etc.
* [Tomar decisiones](http://bit.ly/1xIt1zv)
* [Comunicar, entretener](http://coolmaps.esri.com/#5)
* Etc.

Y no existen una combinación de tecnologías ganadora, siempre depende de variables como la complejidad del proyecto, la experiencia del equipo, la vida estimada del proyecto, etc. 

En esta charla veremos cómo con la API Jasvascript de ArcGIS podemos crear aplicaciones que usen: Polymer / Ember / Bootstrap / Angular / ...

## Bio de ponente

Informático de profesión y emprendedor de vocación. Desde 2009 desarrollando webs y emprendiendo proyectos desde 2007. He trabajado en varias startups, visitado y trabajado fugazmente en Silicon Valley, etc. Actualmente soy organizador de las comunidades de [Iniciador Madrid](http://iniciador.com/madrid) (emprendedores) & [Geo Developers](geodevelopers.org/members). Además trabajo en [Esri España](http://www.esri.es) como responsable de los programas de desarrolladores y emprendedores.

+info: [rauljimenez.info](http://www.rauljimenez.info) & [linkedin](es.linkedin.com/in/jimenezortegaraul)

**Comment by alexfernandez** [comment]
¡Muy completo, gracias! En principio iría para noviembre, salvo bajas de última hora. ¿La ves más de iniciación, o avanzada?

**Comment by hhkaos** [comment]
Gracias Alex, pues yo diría que hace falta un nivel medio de Javascript, no creo que de tiempo a entrar en demasiados detalles pero sí que veremos algún código más avanzado.

En Noviembre yo podría si fuese a finales, es el mes que más jaleo tengo ^_^.

**Comment by alexfernandez** [comment]
Buenas, volvemos a la carga después de las vacaciones. ¿Estarías disponible para dar esta charla en marzo?

**Comment by hhkaos** [comment]
Buenas Alex!,

Pues la primera quincena estaré en EEUU, qué tal la semana del 21 al 25?

Un abrazo,
Raúl

----------------------------------------------------------------------------------------------------------------
Raúl Jiménez Ortega <http://www.rauljimenez.info/>
*Urgent contact:* *+34 652 38 43 50 *

* <http://rauljimenez.info/> **
<https://es.linkedin.com/in/jimenezortegaraul> **
<https://github.com/hhkaos>
<https://plus.google.com/+RaulJimenezOrtega/posts> [image:
http://rauljimenez.info/skype.html] <http://rauljimenez.info/skype.html>
<http://www.twitter.com/hhkaos>  <https://www.youtube.com/user/HHKaoS> **
<http://diigo.com/user/hhkaos/> **
<http://stackoverflow.com/users/3541972/hhkaos>*

2016-01-12 22:23 GMT+01:00 Alex Fernández <notifications@github.com>:

**Comment by alexfernandez** [comment]
Sería perfecto, el 24 es (pen)último jueves del mes que es cuando nos solemos reunir. ¿Te apunto pues?

**Comment by hhkaos** [comment]
Perfect! :), me lo apunto.

Thx!

**Comment by alexfernandez** [comment]
¿Seguimos disponibles para el 24 de marzo? Si es así, empiezo a moverla.

**Comment by alexfernandez** [comment]
Ups, el 24 de marzo es Semana Santa. ¿Estás disponible el 30 de marzo?

**Comment by hhkaos** [comment]
Hi Alex!

Perfect, día 30 pues me paso por Madrid (que me he mudado temporalmente a
Ciudad Real a vivir con la novia), pero no problem.

Un abrazo desde California!
Raúl
P.D: Hoy voy a ver a Douglass Crockford
<http://www.esri.com/events/devsummit>!! :DDD

----------------------------------------------------------------------------------------------------------------
Raúl Jiménez Ortega <http://www.rauljimenez.info/>
*Urgent contact:* *+34 652 38 43 50 *

* <http://rauljimenez.info/> **
<https://es.linkedin.com/in/jimenezortegaraul> **
<https://github.com/hhkaos>
<https://plus.google.com/+RaulJimenezOrtega/posts> [image:
http://rauljimenez.info/skype.html] <http://rauljimenez.info/skype.html>
<http://www.twitter.com/hhkaos>  <https://www.youtube.com/user/HHKaoS> **
<http://diigo.com/user/hhkaos/> **
<http://stackoverflow.com/users/3541972/hhkaos>*

**Comment by alexfernandez** [comment]
Qué suerte :)

Espera a que te confirme, a ver qué me dicen de impact hub...

**Comment by hhkaos** [comment]
Okey! :D

----------------------------------------------------------------------------------------------------------------
Raúl Jiménez Ortega <http://www.rauljimenez.info/>
*Urgent contact:* *+34 652 38 43 50 *

* <http://rauljimenez.info/> **
<https://es.linkedin.com/in/jimenezortegaraul> **
<https://github.com/hhkaos>
<https://plus.google.com/+RaulJimenezOrtega/posts> [image:
http://rauljimenez.info/skype.html] <http://rauljimenez.info/skype.html>
<http://www.twitter.com/hhkaos>  <https://www.youtube.com/user/HHKaoS> **
<http://diigo.com/user/hhkaos/> **
<http://stackoverflow.com/users/3541972/hhkaos>*

**Comment by alexfernandez** [comment]
Me dicen de ImpactHub que el 31 a las 19h, ¿te viene bien?

**Comment by hhkaos** [comment]
Perfect :). me lo apunto! ^_^

**Comment by alexfernandez** [comment]
¡Publicado! http://www.meetup.com/es-ES/madridjs/events/229604536/

**Comment by hhkaos** [comment]
Perfect :D

----------------------------------------------------------------------------------------------------------------
Raúl Jiménez Ortega <http://www.rauljimenez.info/>
*Urgent contact:* *+34 652 38 43 50 *

* <http://rauljimenez.info/> **
<https://es.linkedin.com/in/jimenezortegaraul> **
<https://github.com/hhkaos>
<https://plus.google.com/+RaulJimenezOrtega/posts> [image:
http://rauljimenez.info/skype.html] <http://rauljimenez.info/skype.html>
<http://www.twitter.com/hhkaos>  <https://www.youtube.com/user/HHKaoS> **
<http://diigo.com/user/hhkaos/> **
<http://stackoverflow.com/users/3541972/hhkaos>*

**Comment by hhkaos** [comment]
Alex una última pregunta, de cuánto tiempo dispongo más o menos? :)

Un abrazo!

**Comment by alexfernandez** [comment]
Cuenta con una media hora más o menos (prorrogable unos minutos). Por cierto, va a ir @javiervelezreyes a presentaros.
