### ISSUE TITLE
At your service!

### ISSUE THREAD

**Issue by delapuente** [madridjs/talks#16]
Esta es una charla sobre aplicaciones web progresivas, en particular sobre [_Service Workers_](https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API/Using_Service_Workers) y sus aplicaciones más allá de el cacheo de recursos. Se trata de la misma charla que ofrecí en la [Codemotion 2015](http://delapuente.github.io/presentations/at-your-service/#/), pero con un catálogo de ejemplos ampliado. El conjunto de ejemplos puede encontrarse bajo la categoría _Beyond Offline_ en https://serviceworke.rs

---
Mi nombre es Salva ([@salvadelapuente](https://twitter.com/salvadelapuente) / [delapuente](https://github.com/delapuente)) y trabajo como ingeniero para Mozilla en la iniciativa [WADI]() (_Web Application Developer Initiative_) que pretende impulsar el desarrollo de aplicaciones web y educar sobre las tecnologías que las hagan posibles. Anteriormente trabajé para Telefónica I+D en Firefox OS y he sido mentor en Iron Hack, Tetuan Valley y H4ckademy de JavaScript y Python.

**Comment by alexfernandez** [comment]
Buenas, Salva, ¿estarías disponible para dar la charla el 30 de este mes?

**Comment by delapuente** [comment]
Sí, perfecto. ¿A qué hora?

**Comment by alexfernandez** [comment]
Sería a las 19h, pero espera que confirme con los del ImpactHub.

**Comment by alexfernandez** [comment]
Me dicen de ImpactHub que el 31 a las 19h, ¿te viene bien?

**Comment by alexfernandez** [comment]
Buenas, Salva, necesito confirmación para el día 31 a las 19h. ¡Gracias!

**Comment by delapuente** [comment]
Perdona Alex. ¿Habría alguna forma de que fuera a las 19.30h? Tengo una reunión importante a las 18.30 con gente de San Francisco y por eso estos horarios tan tarde.

**Comment by alexfernandez** [comment]
No hay problema, la dejamos la segunda y así cae a las 19:30. Confirmado entonces, ¡publico!

Gracias :)

**Comment by delapuente** [comment]
¿Cuánto es el tiempo que tengo para la charla?

**Comment by alexfernandez** [comment]
En principio son 30 minutos, aunque se puede alargar un poquitín: tenemos la sala hasta las 20:30. Cuenta con que la anterior también se pueda alargar un poco. ¡Publicado! http://www.meetup.com/es-ES/madridjs/events/229604536/

**Comment by delapuente** [comment]
¡Muchas gracias!

**Comment by alexfernandez** [comment]
Salva, irá @javiervelezreyes a presentaros. ¡Suerte!

**Comment by delapuente** [comment]
Perfecto, voy a ver si hago esa reunión desde el hub y así en cuanto salga estoy allí y lo mismo hasta me da tiempo a ver la otra.
