### ISSUE TITLE
TypeScript: Un JavaScript ES6 con tipos, para bien y para mal

### ISSUE THREAD

**Issue by micaelgallego** [madridjs/talks#17]
Descripción de la charla
===
TypeScript es un superconjunto de JavaScript ES6 al que se le añaden tipos y se potencia la orientación a objetos basada en clases. Se podría decir que es un híbrido entre JavaScript y Java/C#. Se está haciendo cada vez más popular porque es el lenguaje recomendado para Angular 2 y porque cada vez más desarrolladores de backend Java/C# se pasan al desarrollo frontend y quieren mismas “herramientas“ de programación. En esta charla abordaremos principalmente cómo TS ha añadido tipos a JS y las ventajas (e inconvenientes) de esa incorporación.

Bio del ponente
====
Micael Gallego es un desarrollador apasionado por Java desde que acabó la carrera. Es profesor de Programación Concurrente y Aplicaciones Web en la Universidad Rey Juan Carlos. Desarrolló su tesis doctoral en el ámbito de los algoritmos de optimización. Ha pasado por todos los roles en el mundo del desarrollo software, incluso ha hundido su propia startup tecnológica. Actualmente es desarrollador Java senior en el proyecto open source Kurento.org de transmisión de vídeo con WebRtc, así que podéis ver sus vergüenzas en GitHub. Cada vez está más interesado por el desarrollo frontend y con node.js. Twitter: @micael_gallego About.me: https://about.me/micael.gallego

**Comment by alexfernandez** [comment]
Buenas, Micael, ¿estás disponible para dar esta charla el próximo jueves 26? ¡Gracias!

**Comment by micaelgallego** [comment]
Buenas, este mes lo tengo complicado. Hasta finales de Junio no tengo disponibilidad. Lo siento.

En cualquier caso, esa misma semana, el martes 24, hablaré de TypeScript en el MadridJUG (http://www.meetup.com/es-ES/MadridJUG/events/230763932/)... Aunque esta charla será desde “el otro lado” ;)

**Comment by alexfernandez** [comment]
¡Lástima! Hablamos.

**Comment by alexfernandez** [comment]
Buenas, @micaelgallego, ¿y para el jueves 29 de septiembre estás disponible? ¡Gracias!

**Comment by alexfernandez** [comment]
Buenas, me dicen que mejor el miércoles 28, ¿te viene bien? Responde, please, o tenemos que pasar turno.

**Comment by micaelgallego** [comment]
Ese día complicado. Buscamos otra fecha?

**Comment by alexfernandez** [comment]
Vale, a ver en octubre.

**Comment by alexfernandez** [comment]
Buenas, el siguiente encuentro será seguramente el 27 de este mes, ¿qué tal lo tenemos?

**Comment by alexfernandez** [comment]
Por silencio administrativo, cerramos esta charla. Please, reabre cuando tengas disponibilidad.

**Comment by micaelgallego** [comment]
Perdón por no haber contestado a tiempo. Cuando tenga disponibilidad me pongo en contacto con vosotros de nuevo.
