### ISSUE TITLE
Fable o cómo escribir un compilador a JS

### ISSUE THREAD

**Issue by alfonsogarciacaro** [madridjs/talks#19]
# Descripción de la charla

Fable es un compilador de F# a JS. "¿Otro más?", se oye en la sala. Sí, otro compilador más pero (espero) que esta no sea otra charla más. Porque en lugar de hacer (vanos) esfuerzos en convencer a los programadores JS de que se pasen a un lenguaje "serio", lo que se pretender es mostrar como Fable puede ayudar a que dos fantásticas tecnologías colaboren juntas usando el propio compilador como ejemplo y así de paso adentrarnos aunque sea superficialmente en la teoría de los lenguajes.

Los amantes de la polémica se verán decepcionados porque no habrá una cruenta guerra de lenguajes (aunque se explicará brevemente qué puede aportar F# al desarrollo front-end), Fable no nace desde el rechazo a JS sino desde el reconocimiento al fenomenal ecosistema que ha florecido alrededor de este pequeño gran lenguaje, y la ilusión de que un compañero, F#, de alma funcional y ambición multiparadigma pueda formar parte de él.

# Bio del ponente

Alfonso García-Caro es un desarrollador .NET y JS de ecléctico background. Graduado en Filología y tras vivir en Japón y Alemania volvió a la programación acuciado por la necesidad de aprender constantemente. En los últimos años interesado especialmente en la programación funcional y el desarrollo de aplicaciones web y móviles, pero también iniciándose en el mundo de Machine Learning. Colaborador en varios proyectos open source y creador de Fable (compilador de F# a JS), ha realizado presentaciones en varios países (US, UK, Japón, España). En la actualidad vive en Madrid, trabaja para toggl.com y prepara la publicación de un libro. Twitter: alfonsogcnunez

**Comment by alexfernandez** [comment]
Alfonso, ¿puede ser la charla el jueves 26? ¿Tienes disponibilidad para el miércoles 25, si se da el caso?

**Comment by alfonsogarciacaro** [comment]
Jueves 26 perfecto :+1: El miércoles me vendría peor :(

**Comment by alfonsogarciacaro** [comment]
¿Al final se organiza la charla entonces?

**Comment by alexfernandez** [comment]
En principio sí, estamos buscando sitio todavía.

**Comment by alexfernandez** [comment]
¡Ya tenemos el sitio! El Impact Hub como siempre. Ahora creo el Meetup.

**Comment by alfonsogarciacaro** [comment]
¡Genial, muchas gracias!

**Comment by alexfernandez** [comment]
¡Publicado en [Meetup](http://www.meetup.com/es-ES/madridjs/events/231216532/)! Please, comprueba que esté todo correcto. El maestro de ceremonias será @javiervelezreyes porque a mí me pilla de viaje. ¡Suerte!
