### ISSUE TITLE
UI Kits en React: el caso de React Toolbox

### ISSUE THREAD

**Issue by javivelasco** [madridjs/talks#20]
### Descripción de la charla

Hace ya casi un año del primer commit de [React Toolbox](www.react-toolbox.com). En principio no fue más que un intento por mejorar la implementación de [Material UI](www.material-ui.com) utilizando CSS en lugar de estilos en línea, pero la incorporación de css modules, la atención a los detalles y una nueva forma de documentación impulsó la proyecto a una popularidad tal que hoy roza las 3300 stars en Github.

En esta charla veremos el proceso de desarrollo y los retos afrontados en la construcción de este ui-kit. Para ello haremos una introducción a React y a css modules y pasando por los problemas de styling/theming que existen a día de hoy y cómo estamos intentando resolverlos. Dependiendo del tiempo podríamos incluso ver un pequeño ejemplo de live coding utilizando la librería para ayudaros a empezar a usarla en vuestros prototipos.

### Bio del ponente

[Javi Velasco](http://twitter.com/javivelasco) es desarrollador frontend en [Audiense](http://www.audiense.com) y autor de [React Toolbox](www.react-toolbox.com). Aunque a día de hoy escribe principalmente Javascript ha trabajado en Ruby, Python en multitud de roles. Actualmente está muy involucrado en el ecosistema de React y trata de encontrar el punto en que dicho ecosistema se encuentra con las buenas prácticas y la *clean architecture*.

**Comment by alexfernandez** [comment]
Buenas, @javivelasco, entiendo que es una charla avanzada, y que además podemos alargarla a una hora. ¿Estás disponible para finales de mes, por ejemplo para el 30?

**Comment by javivelasco** [comment]
Estaré! La charla no tiene por qué ser muy avanzada pero hay material para una hora tranquilamente :)
Confirmo que el día 30 estaré por aquí!

**Comment by alexfernandez** [comment]
Hecha, cerrando.
