### ISSUE TITLE
Node.js EE o Java as a library. 

### ISSUE THREAD

**Issue by cesarvr** [madridjs/talks#21]
## Descripción

Quiero presentaros un proyecto en el que trabajo en mi tiempo libre, trata de un node.js add-on escrito C++11 que te permite ejecutar java-code dentro de node.js y así poder acceder a un gran ecosistema de librerías disponibles como API para PDF: (pdfbox, itext) Motores de búsqueda: solr. 

- por que node.js ?
  - extensibilidad con C++
  - libUV
  - chakracore 
  - Debilidades 
- Ella add-on 
  - como funciona ?
  - demo 

## Bio

Actualmente trabajo para Red Hat mobile desarrollando aplicaciones móviles usando node.js en el lado backend, en mi tiempo libre me gusta desarrollar motores gráficos, y últimamente muy interesado en las interioridades de node.js/chakracore.  

## Bio

Actualmente trabajo para Red Hat mobile desarrollando aplicaciones móviles usando node.js en el lado backend, en mi tiempo libre me gusta desarrollar motores gráficos, y últimamente muy interesado en las interioridades de node.js/chakracore.

**Comment by alexfernandez** [comment]
Esta charla la veo más apropiada para Node.js Madrid, así que la cerramos aquí.
