### ISSUE TITLE
Mip- App

### ISSUE THREAD

**Issue by ardiadrianadri** [madridjs/talks#22]
Todos hemos oído hablar de NativeScript; ese framework que te permite programar en JS una aplicación que es nativa e híbrida al mismo tiempo. También hemos oído hablar de los proyecto IoT: esas aplicaciones capaces de comunicar nuestros dispositivos con las máquinas de nuestro entorno para, por ejemplo, manejar los termostatos de casa cuando estamos fuera, controlar drones o que, nuestras pulseras, nos digan que comer una hamburguesa en un restaurante americano es saltarse la dieta (que haríamos sin ellas...)

Nosotros hemos unido los dos mundos para programar una aplicación hibrida y nativa que controla un robot MIP (que no es tan útil como la pulsera pero tiene bandeja para bebidas). Queremos compartir con vosotros las tecnologías utilizadas en el proceso, el uso de la librería de NativeScript para bluetooth y una simpática demo con nuestro MIP. Os enseñaremos que, programar aplicaciones que hagan uso del BLE para la comunicación con dispositivos, no es difícil y, con un poco de esfuerzo, cualquiera puede tener su propia app de IoT.  

¿Quienes somos nosotros? Somo ngBraves, un grupo de 5 desarrolladores que nos reunimos para programar aplicaciones fuera del ámbito empresarial. Buscamos aprender mas, hacer cosas que nos gustan sin cerrarnos a nada y difundir lo aprendido. A pesar de tener solo 1 mes de vida hemos empezado con muchas ganas y queremos dar muchas charlas como esta. Para quien quiera conocernos o ver en que andamos metidos puede enviarnos un mail a ngbraves@gmail.com.

**Comment by alexfernandez** [comment]
Buenas, @ardiadrianadri: muy interesante. ¿La veis como charla de iniciación o avanzada?

**Comment by ardiadrianadri** [comment]
Hola @alexfernandez: 
No vamos a entrar muy a saco en las tecnologías. Vamos a describir las ventajas de NativeScript, explicaremos las características de Angular 2 que es el pegamento que hace que todo funcione y luego pasaremos a explicar la interfaz del Bluetooth y como usarlo en código JavaScript. En ese sentido, para entender lo que mostramos, basta con saber JavaScript. 

No se si respondo a tu pregunta...

**Comment by alexfernandez** [comment]
Me hago una idea. Queda ya lógicamente para el curso que viene. ¡Gracias!

**Comment by ardiadrianadri** [comment]
Hola gente:

 Perdonar la pregunta ¿Cuando empieza el curso? Quiero decir... ya es septiembre, hoy es el primer día de cole... ¿cuando queréis que hagamos la charla?

**Comment by alexfernandez** [comment]
@ardiadrianadri Ya ha empezado el curso, teníamos que contactar primero a la otra charla que iba primero, pero no están disponibles. ¿El miércoles 28 os viene bien? ¿Una charla de media hora, o de hora completa?

**Comment by ardiadrianadri** [comment]
El Miercoles nos viene un poquito mal. Muchos estamos en Londres por el Angular Connect ( Van a celebrar un partido de robot soccer con el software que vamos a presentar en la charla). ¿No puedes ser en otra fecha?

**Comment by alexfernandez** [comment]
¿El viernes? ¿O lo dejamos ya para otro mes?

**Comment by ardiadrianadri** [comment]
Mejor para Octubre si no te importa. Los viernes los tengo comprometidos y tengo miedo de que, al ser un viernes, la gente haya hecho planes de fin de semana y tengamos poca afluencia de público

**Comment by alexfernandez** [comment]
Vale, ¡sin problemas!

**Comment by alexfernandez** [comment]
Buenas, @ardiadrianadri, ¿te viene bien el próximo jueves 27 de octubre? Otra cosa, ¿la ves como charla de una hora o de media?

**Comment by ardiadrianadri** [comment]
Hola Álex:
El 27 me parece bien. Sobre el tiempo de la charla depende. 30 min sin live coding, 1h con live coding. Te lo dejo a tu elección. El Robot para que puedan jugar los asistentes lo pongo yo

**Comment by alexfernandez** [comment]
@ardiadrianadri Perfecto, ¿me pasas bio del o los ponentes para el Meetup?

**Comment by ardiadrianadri** [comment]
My Bio: 
Soy Adrián Ferreres y el asma, star trek y los videojuegos (no tengo claro en qué orden) me llevaron, a los 11 años, a empezar a programar. Desde entonces no he parado (de tener asma, de ver star trek, de jugar a videojuegos y de programar). 

En 2012 dejé Java para empezar con JavaScript y me gustó… mucho. Me gustó tanto que ahora sólo hago eso. Desde el año paso dedico mi tiempo libre a la programación de apps IoT con BLE lo que me llevo a reunirme con 4 locos mas, formar el grupo de ngBraves y programar una aplicación para controlar un robot MIP que lo esta petando fuera de España. Ahora os la presento a vosotros.

La Bio de Pablo Perez:
Mi nombre es Pablo, soy Ingeniero Software y quizás la mejor palabra
que se adapta a mí es "curioso". Quiero aprenderlo todo, quiero
conocer, adoro los retos y me divierto mucho enfrentándolos, sobre
todo si es en compañía. Mi gran objetivo es lo que yo llamo
Informática Biomédica, lograr que la informática ayude a la gente.

**Comment by alexfernandez** [comment]
¡Actualizado! http://www.meetup.com/es-ES/madridjs/events/234750673/
