### ISSUE TITLE
Gestionar la asincronía en Javascript

### ISSUE THREAD

**Issue by todojs** [madridjs/talks#23]
Con el paso del tiempo han ido apareciendo diferentes modelos de gestión de la programación asíncrona de Javascript. Del paso de callbacks hemos pasado a gestores de eventos, promesas, generadoras y próximamente aparecerá async/await para completar el conjunto de herramientas que podemos utilizar.

Durante esta charla daremos un repaso a todas estas posibilidades, ahondado especialmente en el uso de funciones generadoras y la librería co() como anticipo de async/await.

Se puede consultar un anticipo de lo que se tratará en la charla en:
- [https://www.todojs.com/controlar-la-ejecucion-asincrona/](https://www.todojs.com/controlar-la-ejecucion-asincrona/)
- [https://www.todojs.com/acceder-mongodb-ecmascript-6-desde-nodejs/](https://www.todojs.com/acceder-mongodb-ecmascript-6-desde-nodejs/)

El nivel de la charla va de básico a avanzado y no requiere conocimientos previos sobre este tipo de programación.

Ponente: Pablo Almunia, licenciado en Filosofía, doctor en Informática y master en Administración de Empresas, por lo que termina abarcando desde la metafísica a las finanzas, pasando por algunos temas técnicos que le apasionan como NodeJS, Javascript, MongoDB, etc.

**Comment by alexfernandez** [comment]
¿Estás disponible para el miércoles 28 de septiembre? ¿Media hora o una hora completa?

**Comment by todojs** [comment]
Estoy disponible el miércoles 28 o el jueves 29. Puedo adaptarme al tiempo que sea necesario. En 1 hora es más cómodo, pero si hay que hacerlo en 30 minutos se hace.

**Comment by alexfernandez** [comment]
Vale, pues ¡adjudicado! Dada la escasez de charlas, en principio vamos a hacerla de una hora.

**Comment by alexfernandez** [comment]
¿Se puede incluir una explicación extendida sobre `async`/`await`? Es el futuro, y creo que habrá bastante interés (al menos por mi parte seguro).

**Comment by todojs** [comment]
Sí, claro. Mi idea es explicar desde el principio los conceptos de asincronía en Javascript, pero ir rápidamente al caso con **co()+generadoras** y explicar por qué es equivalente al uso de **async/await**, y que tendremos que cambiar cuando esté disponible (el `co( function*` por `async function` y el `yield` por await).
