### ISSUE TITLE
Acercamiento con sigilo a la programación funcional con JavaScript

### ISSUE THREAD

**Issue by gootyfer** [madridjs/talks#24]
Si queremos empezar a aprender cómo funciona el paradigma funcional, tenemos dos opciones: 1) meternos de lleno a aprender un lenguaje nuevo a la vez que el paradigma, por ejemplo, con Scala; 2) tener un acercamiento con más sigilo, más poco a poco, desde un contexto y un lenguaje conocidos y centrarnos en aprender los conceptos. En esta charla vamos a aproximarnos con sigilo a algunos conceptos de la programación funcional usando nuestro lenguaje favorito. Desde funciones puras y efectos secundarios, hasta a llegar el borde del abismo de las mónadas. Para ello partimos del estupendo [libro del Prof. F. Risby "Mostly Adequate Guide to Functional Programming"](https://drboolean.gitbooks.io/mostly-adequate-guide/content/) y la librería funcional [Ramda](http://ramdajs.com/).

¿Y quién propone esta charla?
Pues soy [Israel Gutiérrez](http://twitter.com/gootyfer), enamorado de JavaScript desde hace años y empezando poco a poco a aprender los principios de la programación funcional, donde soy un novato total. Me encanta la formación y los proyectos de innovación educativa.

**Comment by alexfernandez** [comment]
@gootyfer ¿Es una charla de introducción o avanzada? ¿La ves de media hora, o da para una hora?

**Comment by gootyfer** [comment]
@alexfernandez diría de que un nivel medio, porque se necesita una buena base de JS para entender los conceptos que se introducen. Tengo preparado algo de 30' y creo que es el tiempo justo.

**Comment by alexfernandez** [comment]
La charla de Pablo entró minutos antes que la tuya, y vamos por riguroso orden de llegada. ¡Te avisaremos con tiempo para próximos meses!

**Comment by gootyfer** [comment]
Claro! Si la envié para cubrir el hueco que quedaba. Pero si tengo más tiempo para prepararla, más aprenderé y quedará mejor ;)

**Comment by alexfernandez** [comment]
Buenas, ¿podría ser a finales de febrero? Digamos el 28.

**Comment by gootyfer** [comment]
Hey Álex! Esa semana me pillas en Barcelona :(

**Comment by alexfernandez** [comment]
Vaya, otra vez será :(

**Comment by alexfernandez** [comment]
Estamos de nuevo en ese momento del mes, ¿puedes el próximo miércoles 28 de junio?

**Comment by gootyfer** [comment]
Est vez sí, genial! :)

**Comment by alexfernandez** [comment]
Cool! Te apuntamos pues, enviamos la convocatoria en cuanto confirmemos con el Hub.

**Comment by alexfernandez** [comment]
¿Te dejamos la hora completa para que te explayes?

**Comment by gootyfer** [comment]
La estuve haciendo en t3chfest este año y con 30' fui muy justito de tiempo, pero tanto como 1h?? Y si son 45' más preguntas??

**Comment by alexfernandez** [comment]
Sí, eso perfecto.

**Comment by alexfernandez** [comment]
¡Hecho!
