### ISSUE TITLE
VueJS: La Revolución Sencilla

### ISSUE THREAD

**Issue by RafaelCasuso** [madridjs/talks#25]
# Title / Título

VueJS: La Revolución Sencilla
# Description / Descripción

Nos adentraremos en el framework progresivo de moda VueJS (y su ecosistema) para la composición de un sistema de componentes reactivos que nos permita reflejar una aplicación compleja, incluyendo gestión de estados (con Vuex) y enrutado (con Vue-Router). Veremos el ejemplo de real de su implementación progresiva en una webapp de gestión de contenido y las ventajas que nos ofrece este framework respecto a librerías como React.

# Speaker Bio / Bio del Ponente

Lead Front-End Engineer y Lead NodeJS Engineer con más de 10 años de experiencia en desarrollo de software, Rafael ha trabajado en grandes proyectos como Air Europa, Halcón Viajes, Loterías del Estado o LaCaixa. Ha participado de la revolución JavaScript, tanto en cliente como en servidor. Ha sido ponente en el JSDay2016 y es organizador de la comunidad Bot Development Madrid. 
# Level / Nivel

Intermedio
# Duration / Duración

45 min

**Comment by alexfernandez** [comment]
Buenas, ¿podría ser a finales de febrero? Digamos el 28.

**Comment by RafaelCasuso** [comment]
Hola,

Sí, perfecto. Ningún problema.

Un saludo.

**Comment by alexfernandez** [comment]
Perfecto, ¡nos veremos [en Impact Hub](https://www.meetup.com/es-ES/madridjs/events/237536476/) a las 19h!
