### ISSUE TITLE
(DIY) Crea tu propio notificador de Twitter.

### ISSUE THREAD

**Issue by isabelcabezasm** [madridjs/talks#26]
# Title / Título

(DIY) Crea tu propio notificador de Twitter.
# Description / Descripción

Ha llegado el "JavaScript de las Cosas". 
Descubre un nuevo mundo de IoT programado desde tu lenguaje favorito. 
Administra sensores, conectores, recopila y envía información a una placa con JavaScript. 

Veremos todo esto analizando un proyecto completo en el que veremos desde las consultas a la API de Twitter, el análisis de los twits a través de Servicios Cognitivos, envío de información a una Intel Edison y notificación sobre la opinión que tienen de ti en forma de códigos de colores.
# Speaker Bio / Bio del Ponente

Isabel Cabezas @isabelcabezasm
Granadina de nacimiento, y madrileña de adopción. 
Integrante de La Comunidad (técnica, no la del anillo) desde hace más de 15 años.
Flirteo con todas las tecnologías que puedo: .NET, JavaScript, C#, IoT, BigData...  
Actualmente trabajo como Technical Evangelist en Microsoft.
# Level / Nivel

Intermedio
(Beginner, Intermediate, Advanced)
(Iniciación, Intermedio, Avanzado)
# Duration / Duración

45 min.
(30 min to one hour)
(30 minutos a una hora)

**Comment by alexfernandez** [comment]
Buenas, Isabel, ¿estás disponible para hacer la charla este mes, digamos del 24 al 26? ¡Gracias!

**Comment by alexfernandez** [comment]
Buenas, @isabelcabezasm, cierro este issue por falta de respuesta. En cuanto puedas dar la charla reabres, ¿vale?
