### ISSUE TITLE
El nuevo GWT 2.8.x - 3.0.x,  la alternativa Java a Javascript.

### ISSUE THREAD

**Issue by manolo** [madridjs/talks#27]
# Title / Título

El nuevo GWT
# Description / Descripción

No es discutible que JS cada vez tiene mas seguidores. A ello ha contribuido que ahora es  mucho mas amigable: nueva especificación, herramientas,  librerías, IDEs, runtime, etc.

Pero aún así muchos desarrolladores y proyectos requieren la seguridad de un lenguaje tipado y una fase de compilación para detectar errores temprano. Esa es la razón de Typescript o GWT.

GWT no ha muerto, se está renovando, y ha cambiado mucho en la última version, especialmente para interactuar fácilmente con el mundo JavaScript. 

En esta charla describiré cómo funciona GWT, dónde se debe considerar su uso y dónde no, y porqué.

Y como no...  espero la polémica a favor y en contra de Java, JS, TS, ...
# Speaker Bio / Bio del Ponente

Vaadin Team member. GWT maintainer. Apache PMC. Jenkins Committer.
# Level / Nivel

Intermedio

(Beginner, Intermediate, Advanced)
(Iniciación, Intermedio, Avanzado)
# Duration / Duración

30 minutos a una hora

**Comment by alexfernandez** [comment]
@manolo Buenas, ¿sigue en pie la propuesta? ¿Podrías hacerla digamos en la última semana de octubre?

**Comment by manolo** [comment]
Ok, me parece bien. Ya tengo algo preparado. Dime día y lugar.

**Comment by alexfernandez** [comment]
¿Puedes el miércoles 25 de octubre?

**Comment by manolo** [comment]
Yep, perfecto.

**Comment by manolo** [comment]
una cosa, preferiría martes o jueves, ¿es posible? no me acordaba que los miércoles normalmente tengo compromisos con los críos

**Comment by manolo** [comment]
Si,  pero intenta que sean los otros días, para no que hacer cuadres familiares ;-)

**Comment by alexfernandez** [comment]
@manolo ¿Me pasas un correo para agilizar? Vamos a intentar que sea el martes 31. ¡Gracias!

**Comment by alexfernandez** [comment]
¡[Hecho](https://www.meetup.com/es-ES/madridjs/events/244455036/)!
