### ISSUE TITLE
The (Awesome) Future of Web Apps

### ISSUE THREAD

**Issue by jadjoubran** [madridjs/talks#28]
# Title / Título

The (Awesome) Future of Web Apps
# Description / Descripción

The web is becoming more and more powerful everyday, especially with the launch of Progressive Web Apps. PWAs are experiences that combine the best of the web and the best of apps. You can now build web apps that run from your home screen, receive push notifications & work offline.

Join this talk for an interactive introduction into the world of Progressive Web Apps.
# Speaker Bio / Bio del Ponente

Back when he was 19, Jad founded eTobb, a startup that connects patients & doctors in the middle east. Since then, he's been on a mission to inspire developers, by presenting advanced topics & best practices at conferences around the world. He's also passionate about open source and loves teaching at Le Wagon.
# Level / Nivel

Beginner
(Beginner, Intermediate, Advanced)
# Duration / Duración

45 minutes

**Comment by alexfernandez** [comment]
Jad, what dates would suit you better? Would November 30th be OK?

**Comment by jadjoubran** [comment]
November 30th would be great
