### ISSUE TITLE
Arquitectura de web components con ng2 npm para 100 aplicaciones web

### ISSUE THREAD

**Issue by cbastos** [madridjs/talks#29]
# Title / Título
Arquitectura de web components con ng2 npm para 100 aplicaciones web

# Description / Descripción
Mostraremos el planteamiento de infrastructura, arquitectura lógica y arquitectura física inicial para el desarrollo de 100 aplicaciones web por un equipo de 100 desarrolladores con reutilización de componentes, cómo utilizar un core común de utilidades para autorización, autenticación, errores, trazas, etc. Todo esto con angular2, webpack, testing con karma, sass, etc.

# Speaker Bio / Bio del Ponente
Carlos Bastos programa desde hace 11 años y trabaja de arquitecto de frontend desde hace 4. Ha liderado el front end de proyectos de gran tamaño (>100 desarrolladores, producto con millones de usuarios) tanto públicos como privados, y también ha trabajado como consultor y ha dado formación a grandes empresas.
Es un apasionado del código limpio, patrones, principios de diseño, buenas prácticas, programación orientada a objetos y en general de mejorar.

# Level / Nivel
Advanced.

# Duration / Duración
1 hora

**Comment by cbastos** [comment]
La charla que propongo es una evolución destilada de ésta:
https://www.youtube.com/watch?v=hxAT9kc46UA

**Comment by sebelga** [comment]
Acabo de ver el vídeo y muy interesante! Gracias por compartir tu arquitectura y ojalá puedas dar una charla sobre ella. Un saludo!

**Comment by alexfernandez** [comment]
Buenas, @cbastos, ¿estás disponible a finales de este mes para dar la charla?

**Comment by cbastos** [comment]
Buenas! el sábado 21 de Octubre voy a la DosConf, ¿cuándo teníais en mente poder darla? :)

**Comment by alexfernandez** [comment]
Esto sería del 24 o el 26 de octubre.

**Comment by cbastos** [comment]
El 26 tengo un evento de mi empresa (plain concepts web day) en el que voy como speaker y el 24 me parece un poco forzado al estar entre 2 eventos. ¿Podría ser la semana siguiente o el mes siguiente?

**Comment by alexfernandez** [comment]
Vale, lo dejamos para el mes que viene si quieres.

**Comment by cbastos** [comment]
Genial, ¿fijamos ya la fecha ?

**Comment by alexfernandez** [comment]
En principio para la última semana, si tienes problemas de disponibilidad dime y haremos lo que podamos.

**Comment by cbastos** [comment]
El 28 martes o 30 jueves de Noviembre puedo sin problema! ;)

**Comment by alexfernandez** [comment]
Pues en principio el 30 de noviembre 👍

**Comment by cbastos** [comment]
Perfecto! :)

**Comment by alexfernandez** [comment]
¡Pedida sala!

**Comment by cbastos** [comment]
Genial! :) Gracias!
