### ISSUE TITLE
CasperJS – Navega con el Piloto Automático

### ISSUE THREAD

**Issue by asanzdiego** [madridjs/talks#3]
# DESCRIPCIÓN DE LA CHARLA

[CasperJS](http://casperjs.org/) es una herramienta que mediante scripts escritos en JavaScript, nos permite simular una navegación web desde un terminal.

¿Y para qué demonios querríamos algo así? Pues en mi caso para automatizar tareas repetitivas que a veces tengo que realizar en un navegador web.

Mi intención, en esta charla, es mostrar las posibilidades que ofrece esta herramienta, y realizar un pequeño ejemplo ilustrativo.

# OTROS DATOS

Nivel intermedio.

Sería repetír la charla que dí el 13 de febrero de 2015 en el [t3chfest](https://techfest.uc3m.es/programa/casperjs-navega-con-el-piloto-automatico-2/)

[Slides de la charla](https://www.slideshare.net/asanzdiego/t3chfest-casperjs-navega-con-el-piloto-automtico) y [Código de la charla](https://github.com/asanzdiego/casperjs-examples)

# BIO PONENTE

Empecé desarrollando aplicaciones web, hasta que di el salto a la docencia. Un día me dio por crear [HackathonLovers](http://hackathonlovers.com), un grupo para amantes de la programación y el emprendimiento. Actualmente soy Asesor TIC en el Centro Regional de Innovación y Formación del Profesorado de la Comunidad de Madrid. Además colaboro puntualmente como formador especializado en desarrollo.

[Adolfo Sanz De Diego](http://about.me/asanzdiego)

**Comment by alexfernandez** [comment]
¡Buenas, Adolfo! Podemos hacer esta charla a finales de abril, te avisaremos con algunas semanas de antelación.

**Comment by asanzdiego** [comment]
Perfecto!!!

**Comment by alexfernandez** [comment]
Buenas, ¿te viene bien este jueves 24 de septiembre?

**Comment by asanzdiego** [comment]
Justo ese día no puedo -__-

**Comment by alexfernandez** [comment]
¡Lástima! Pasamos palabra.

**Comment by alexfernandez** [comment]
Adolfo, ¿sigues interesado en dar la charla, o la cerramos? Lleva un montón de tiempo estancada...

**Comment by asanzdiego** [comment]
La cierro Alex. :)

**Comment by alexfernandez** [comment]
Gracias :)  Si tienes más propuestas, ¡ya sabes!
