### ISSUE TITLE
JavaScript & Node.js: La "Enterprise Edition" con TypeScript y InversifyJS

### ISSUE THREAD

**Issue by remojansen** [madridjs/talks#30]
# Título

**JavaScript & Node.js: La "Enterprise Edition" con TypeScript y InversifyJS**

# Descripción
En esta charla exploraremos como TypeScript y librerías como InversifyJS pueden ayudarnos a implementar una arquitectura que se adhiere a patrones de diseño para la construcción de sistemas empresariales, en los se requieren un especial esfuerzo en infraestructura y un correcto nivel de abstracción para maximizar factores como la escalabilidad o el mantenimiento del sistema.

# Bio del Ponente

<img src="https://avatars1.githubusercontent.com/u/10656223?v=3&u=cfb8f6b1dcdb472937d35b8eca15dced2771f677&s=400"  width="100"  align="right">

Remo H. Jansen es un desarrollador web, Microsoft MVP, [autor](https://www.amazon.es/Learning-TypeScript-Remo-H-Jansen-ebook/dp/B0151N0G7W), ponente, emprendedor, amante de la tecnología y un entusiasta del Internet. Remo es el organizador de los meetups de [Open Source](https://www.meetup.com/dublin-oss/) y [TypeScript](https://www.meetup.com/Dublin-TypeScript-Meetup/events/236277874/) en Dublin (Irlanda) y el autor de [InversifyJS](https://github.com/inversify/InversifyJS).

# Nivel

Intermedio

# Duración

60 minutos

# Notas
Solo voy a estar en Madrid un par de días porque voy a ir al evento "MVP Community Connection" de Microsoft así que los días que podre hacer la charla son:

- 31 de Mayo (Miércoles)
- 1 de Mayo (Jueves)

Gracias :clap:

**Comment by remojansen** [comment]
Ya tengo confirmado los vuelos :smile: asi que estoy disponible en esas fechas. Si es posible el Miercoles me va mejor que el Jueves pero si tiene que ser el Jueves no pasa nada :wink:

**Comment by alexfernandez** [comment]
@remojansen ¿Entiendo que es 31 de mayo y 1 de junio? Intentaremos que sea el miércoles 31 de mayo.

**Comment by remojansen** [comment]
Si, @alexfernandez el Miércoles 31 de Mayo me viene perfecto :+1:

**Comment by alexfernandez** [comment]
Buenas, al final esta charla se hizo en Node.js Madrid, la cierro.
