### ISSUE TITLE
Optimización del rendimiento en navegadores

### ISSUE THREAD

**Issue by hhkaos** [madridjs/talks#31]
# Title / Título
Optimización del rendimiento en navegadores

# Description / Descripción
El objetivo de esta charla es introducir a aquellos profesionales **nuevos en este campo** algunos conceptos clave a la hora de mejorar la experiencia de usuario en nuestra página, para ello veremos qué operaciones se ejecutan a la hora de renderizar una página,  en qué orden lo hacen, qué factores afectan más en los tiempos de respuesta, etc. También repasaremos algunas de las herramientas que nos ofrece Chrome DevTools para detectar posibles cuellos de botella y veremos un caso práctico de optimización.

La charla estará basada en los contenidos de [este curso gratuito de Udacity](https://www.udacity.com/course/browser-rendering-optimization--ud860).

# Speaker Bio / Bio del Ponente
Desarrollador web desde 1999 en continuo aprendizaje, no soy un experto en este tema pero siempre me gusta marcarme nuevos retos y creo que ofrecerme para dar charlas de aspectos que desconozco siempre es un buen reto para obligarme a seguir reciclándome, crecer profesionalmente y aportar algo a la comunidad. 

Actualmente trabajo en [Esri](hhkaos.github.io/awesome-arcgis/) como "*Head of Developers & Startups program*", soy padre de un futuro developer ;P, dinamizo [geodevelopers.org](http://www.geodevelopers.org/), coordino [Iniciador Madrid](http://iniciador.com/madrid), colaboro en [Code for Spain](http://www.codeforspain.org/) y [Startup Weekend](http://www.up.co/communities/spain/madrid/startup-weekend/5110#event-organizers), intento terminar el libro [cursohtml5desdecero.com](http://cursohtml5desdecero.com/), algunas cosas más (+info: [rauljimenez.info](http://rauljimenez.info/experiencia/)).

# Level / Nivel
Medio-Avanzado

# Duration / Duración
1h

**Comment by alexfernandez** [comment]
Buenas, @hhkaos, ¿estás disponible para hacer esta charla a finales de octubre?

**Comment by alexfernandez** [comment]
Buenas, @hhkaos, ¿qué tal te viene a finales de febrero?

**Comment by hhkaos** [comment]
Hi Alex!! Perdona lo primero que no vie tu comentario el 9 de Oct (se ve que tenía las notificaciones mal configuradas).

Pues ahora me viene un poco mal porque justo para entonces tengo viaje a USA (además que voy algo pillado de tiempo). ¿Podríamos planificarlo para mediados de año o así?

Sorry again!

**Comment by alexfernandez** [comment]
Perfecto, te avisaremos con tiempo para que lo puedas preparar. ¡Gracias!

**Comment by alexfernandez** [comment]
Buenas, @hhkaos, volvemos a la carga: ¿qué tal a finales de abril?

**Comment by hhkaos** [comment]
Ey @alexfernandez, si podemos planificar para Mayo sí que podría organizarme. Para Abril voy apurado con algunos temas que tengo acumulados.  O si necesitas a alguien y quieres que veamos otro tema que me lleve menos tiempo prepararme podemos comentar por tlf ;).

**Comment by alexfernandez** [comment]
¡Claro, @hhkaos! ¿Cuándo te viene bien en mayo?

**Comment by alexfernandez** [comment]
@hhkaos Vale, ¿vamos a ponerla para el 29 de mayo si te parece?

**Comment by hhkaos** [comment]
Perfecto, thx! :+1: :smile:

**Comment by alexfernandez** [comment]
Hecha: https://www.meetup.com/es-ES/madridjs/events/250425040/.
