### ISSUE TITLE
Vuelta a la plataforma con Web Components v1 y ES6

### ISSUE THREAD

**Issue by jroji** [madridjs/talks#32]
# Title / Título
Vuelta a la plataforma con Web Components v1 y ES6

# Description / Descripción

El objetivo de esta charla es hablar de el último estándar de Web Components v1 y Shadow Dom v1. Mostraremos ejemplos y alternativas nativas a librerías y frameworks orientados a componentes para cuestionarnos si siguen siendo imprescindibles. Además de esto, veremos como hacer uso de elementos de ES6 como los Proxies o las propiedades nativas de los web components para  construir nuestra propia "librería de componentes" básica.

# Speaker Bio / Bio del Ponente
Frontend Team Leader en Sngular y formador en Fictizia, donde comparte su pasión por las arquitecturas web, propiciando historias de amor estricto entre desarrolladores y código. Siempre buscando nuevos retos y probando todo lo que puede. Defensor de lo estándar, crítico con el código del día anterior, enfocado actualmente en sacar el máximo partido a Angular 2 y Polymer, siempre apostando por soluciones nativas frente a frameworks. 

# Level / Nivel
Intermedio

# Duration / Duración
45 minutos

**Comment by alexfernandez** [comment]
Buenas, @jroji, ¿qué disponibilidad tienes para dar la charla?

**Comment by alexfernandez** [comment]
¿Te vendría bien, digamos, a finales de febrero?

**Comment by jroji** [comment]
Buenas, en febrero voy a estar un poco hasta arriba. A partir de la segunda semana de marzo (12) sin problemas

**Comment by alexfernandez** [comment]
Perfecto, te avisaremos con antelación.

**Comment by alexfernandez** [comment]
Buenas, @jroji, volvemos a la carga: ¿qué tal a finales de abril?

**Comment by alexfernandez** [comment]
Buenas, ¿estás disponible para finales de mes?

**Comment by alexfernandez** [comment]
Cierro el issue, cuando tengas tiempo otra vez lo puedes reabrir.
