### ISSUE TITLE
Introduction to React Native

### ISSUE THREAD

**Issue by javiercr** [madridjs/talks#33]
# Title
Introduction to React Native

# Description
In this talk we'll introduce [React Native](https://facebook.github.io/react-native/), a framework for building native mobile apps with JavaScript and React. We'll cover how to apply your existing React knowledge to the mobile world and we'll see how to quickly get started creating a new mobile app with [create-react-native-app](https://github.com/react-community/create-react-native-app) and [Ignite CLI](https://github.com/infinitered/ignite).

# Speaker Bio
[Javier Cuevas](https://twitter.com/javier_dev) is CTO and Co-founder of [Gudog](https://gudog.com), a p2p marketplace for dog owners and dog sitters (i.e. Airbnb for dogs).

Before Gudog, Javier was formerly CEO at [Diacode](https://diacode.com), a Ruby on Rails and Elixir/Phoenix consulting firm.

# Level
Beginner - Intermediate

# Duration / Duración
40 min + Q&A

**Comment by javiercr** [comment]
Regarding dates, I could do it any time starting from May 22th :)

**Comment by alexfernandez** [comment]
Buenas, ¿te viene bien hacer la charla a finales de febrero?

**Comment by alexfernandez** [comment]
Buenas, @javiercr, ¿te viene bien hacer la charla a finales de febrero?

**Comment by alexfernandez** [comment]
Nuevo intento, @javiercr: ¿te viene bien a finales de abril?

**Comment by alexfernandez** [comment]
Última llamada a @javiercr: ¿te viene bien a finales de septiembre?

**Comment by javiercr** [comment]
@alexfernandez disculpa, no había visto las notificaciones 😔 . Me va bien, ¿sabes fecha exacta? Gracias!

**Comment by javiercr** [comment]
¿En domingo?

**Comment by javiercr** [comment]
Martes 25 bien :)

**Comment by alexfernandez** [comment]
¡Perfecto! Envíame tu dirección de correo a alexfernandeznpm@gmail.com para que te copie en la reserva de sala.

**Comment by alexfernandez** [comment]
¡Hecha, gracias!
