### ISSUE TITLE
Rasterización y renderización 3D en Javascript Vanilla

### ISSUE THREAD

**Issue by PRDeving** [madridjs/talks#34]
# Título

Rasterización y renderización 3D en canvas 2D con Javascript Vanilla

# Descripción

Importar un objeto 3D, aplicarle texturas, sombras y efectos y pintarlo en un entorno 2D no es imposible, solo enfermizo de intentar. Desde el proceso de parseo del fichero 3D hasta el fragment shader, descubre como implementar un proceso de renderizado completo.

# Bio del Ponente

Analista Senior de Software en eDreams Barcelona, hacker, investigador, innovador y tarado en general. Enamorado de la tecnología

# Nivel

Charla conceptual básica.

# Duración

40 - 50 minutos

**Comment by alexfernandez** [comment]
Buenas, @PRDeving , ¿te viene bien hacer la charla a finales de febrero?

**Comment by alexfernandez** [comment]
Buenas, @PRDeving , ¿qué tal te viene hacer la charla a finales de abril?
