### ISSUE TITLE
Observables with imagination

### ISSUE THREAD

**Issue by ardiadrianadri** [madridjs/talks#35]
# Observables with imagination

# Description
Reactive programming has been there for over five years, however it is not common to find someone who really knows what an observable is and how it works. It is not a talk, it is a workshop where we will put into practice, from the basics, this kind of things call it reactive programming with the RXJS library

# Speaker Bio / Bio del Ponente
I'm Adrián Ferreres and asthma, star trek and video games (I'm not clear in what order) took me, at age 11, to start coding. Since then I have not stopped (from having asthma, watching star trek, playing video games and coding). In 2012 I left Java to start with JavaScript and I liked it ... a lot. I liked it so much that now I just do that. The last 3 years I have been working only in Angularjs and, since beta 17, in Angular . I have done projects in both technologies within the business scope, which has given me a vision and experience as an architect that I would like to share with you So that we can all learn from each other.

# Level / Nivel
Beginner
(Beginner, Intermediate, Advanced)
(Iniciación, Intermedio, Avanzado)

# Duration / Duración
4 hours... it is a workshop

**Comment by ardiadrianadri** [comment]
Buenas gente:

 Este workshop lo tenia pensando hacer en ngLabs en Septiembre. Tengo el sito, la hora, el lugar... lo tengo todo pero, en vista a la polémica que, injustamente, se ha creado en torno a MadridJS, y como muestra de apoyo incondicional a la labor que lleváis desempeñando los organizadores de este meetup me gustaría publicarlo en vuestro grupo. 

 Como ya lo tengo todo organizado, mas o menos,  cuando nos acerquemos a Septiembre, ya os aviso yo de la fecha final y el sito ¿Ok?

 Por cierto, el workshop será en Inglés porque ya tengo medio apalabrado el streaming y mi intención es que se divulgue por fuera de España.

Saludos:
Adrian Ferreres

**Comment by alexfernandez** [comment]
Buenas, Adrián,

Claro, lo anunciamos en MadridJS. ¡Gracias por el apoyo!

**Comment by alexfernandez** [comment]
Workshop hecho: https://www.meetup.com/es-ES/madridjs/events/243151109/.
