### ISSUE TITLE
Resilient Microservice WebAPIs with REST and API Gateway

### ISSUE THREAD

**Issue by XVincentX** [madridjs/talks#36]
# Title / Título
Resilient Microservice WebAPIs with REST and API Gateway

# Description / Descripción
Splitting your application into a bunch of microservices is a non trivial task with a lot of challenges, that might end up in with a complete different system that’s breaking the clients. Can we fix that somehow? Yes - with REST (the real one) and an API Gateway.

In this presentation I’d like to reharse the REST architectural style (that’s probably one of the most misunderstood concepts and why you should probably hold your horses with using GraphQL); then we will start with a sample monolithic application and slowly break it into multiple microservices.

Problems will start to rise, clients will break and multiple parts of code will be duplicated across the microservices. Here’s the point where I’d like to refactor the API and introduce an API Gateway, and solve these one by one.

At the end of the presentation, you’ll see how we can switch from the monolithic version to the microservice version without breaking the clients at all.
# Speaker Bio / Bio del Ponente

Vincenzo Chianese is an Italian Software developer currently working for LunchBadger. He puts bugs in the code, making sure his coworkers have always something to fix

# Level / Nivel

Intermediate

# Duration / Duración

45 minutes

**Comment by XVincentX** [comment]
@alexfernandez Hay novedades sobra esto?

**Comment by alexfernandez** [comment]
@XVincentX Está en cola, ¿tienes restricciones de fecha? En principio vamos tirando de la lista por orden de entrada, a no ser que haya alguna restricción.

**Comment by XVincentX** [comment]
No no tranquilo, no tengo restricciones. Queria solo saber el estado de la cosa. Espero una tua llamada entonces 👍

**Comment by alexfernandez** [comment]
Buenas, @XVincentX, ¿te viene bien hacerla a finales de febrero?

**Comment by XVincentX** [comment]
Hey,

Me puedes dar una fecha mas precisa? La mayoría de febrero
voy a pasarla en San Francisco, y regreso el 20. Si hacemos
desde el 25, creo que no hay problema.

**Comment by alexfernandez** [comment]
Puedo buscar sala el martes 27 de febrero si te viene bien.

**Comment by XVincentX** [comment]
@alexfernandez 

Si, me sale bien.
Si no tienes la sala tengo aceso (gratis) a aquella de Google en Puerta de Angels. Si quieres podemos tomar esa.

**Comment by alexfernandez** [comment]
¿El Campus Madrid? Hay que pedirla con mucha antelación, creo. Además tenemos compromiso con el Impact Hub.

**Comment by XVincentX** [comment]
Esta bastante libre en la semana 25/2-1/3

Pero si ya teneis compromiso y la sala esta libre, vamos!

**Comment by alexfernandez** [comment]
@XVincentX Si quieres ir pidiéndola, por mí bien. Siempre tenemos tiempo de cancelar más adelante.

**Comment by alexfernandez** [comment]
@XVincentX Parece que no nos responden del Impact Hub. ¿Has encontrado sala en el Campus Madrid?

**Comment by XVincentX** [comment]
Està libre es 26/2 y el 28/2 (7:30 PM) o el 25 (todo el dia).

25/2 a las 7:00?

**Comment by alexfernandez** [comment]
Buenas,

El 25 es domingo, mala fecha. El lunes 26 o el miércoles 28 a las 19:30
podrían ser buenas opciones. Ve reservando si quieres, y si nos responden
del Hub siempre podemos reevaluar.

Alex.

On Mon, Feb 5, 2018 at 11:15 AM, Vincenzo Chianese <notifications@github.com

**Comment by XVincentX** [comment]
Ha! Por esto estaba libre todo el dia! 😄 

Hecho. Te escribo cuando me contestan.

**Comment by alexfernandez** [comment]
¡Gracias!

On Mon, Feb 5, 2018 at 11:28 AM, Vincenzo Chianese <notifications@github.com

**Comment by alexfernandez** [comment]
@XVincentX ¿La quieres hacer en español o en inglés?

**Comment by XVincentX** [comment]
Me gustaría mucho hacerla en Español, pero no creo que tengo bastante fluidez.

Entonces preferiría en Ingles.

Un saludo,

V.

**Comment by XVincentX** [comment]
Hecho! Cerramolos!
