### ISSUE TITLE
Hacking de videojuegos con JavaScript

### ISSUE THREAD

**Issue by karliky** [madridjs/talks#39]
# Title / Título
Hacking de videojuegos con JavaScript
# Description / Descripción

¿Cómo hacen trampas los hackers en los videojuegos? ¿Se puede hackear World Of WarCraft con JavaScript?. En esta charla veremos cómo explorar videojuegos utilizando sólo JavaScript/Node.js. 

Repasaremos diferentes juegos como OverWatch o Guild Wars 2 y explicaré cómo tomar el control de un videojuego incluso llegando a las profundidades de su código ensamblador. No te pierdas esta charla si eres gamer o si te gusta JavaScript.

# Speaker Bio / Bio del Ponente

Hacking e ingeniería inversa en mi tiempo libre. Backend engineer en Audiense por trabajo. Me gusta estudiar cómo funcionan las máquinas virtuales de JavaScript (V8, SpiderMonkey...).

Leo mucho sobre exploradores y de vez en cuando intento montar cometas con bamboo. 

# Level / Nivel
Advanced

# Duration / Duración
50~min

I won't be able to give this talk in December as I will be traveling a lot so it would be great if we can plan it for November.

**Comment by alexfernandez** [comment]
¡Buenas! ¿Cuándo te viene bien dar esta charla en este año?

**Comment by karliky** [comment]
Pues no sé si podéis proponerme vosotros alguna fecha 😬

**Comment by karliky** [comment]
Marzo 1-3 y 14-16 no podría porque lo tengo reservado.

**Comment by alexfernandez** [comment]
¡Perfecto! Si no tienes ninguna restricción entonces te llamaremos cuando te toque en la cola :)

**Comment by karliky** [comment]
Al final lo he movido a `Software Crafters Madrid` porque esta issue la abrí en octubre y se me hacía demasiado largo esperar por la cola de gente que había y quería verla. Pero espero abriros otra issue para hablar de JavaScript pronto :).

**Comment by alexfernandez** [comment]
¡Vaya, lo siento! Esperamos tu nueva charla, o avísanos de cuándo quieres hacerla y la adelantamos :)
