### ISSUE TITLE
The new HTTP/2 protocol

### ISSUE THREAD

**Issue by ipeychev** [madridjs/talks#4]
Description:
The new version of HTTP protocol is coming!
HTTP 1.1 forced both developers and browser vendors to invent different tricks in order to make sites to load and run faster. HTTP/2 will provide significant improvements overt HTTP 1.1 and many of these tricks will become unnecessary. On their place, Web developers will introduce new ways for optimizing the pages. 
In this talk I will give an introduction the protocol and emphasize why is it so important for the Web development workflow.

Bio:
Iliyan Peychev is a Software Engineer and UI Infrastructure Lead in Liferay Inc. He started as C developer fourteen years ago, when he was writing software for banks and other financial institutions. Then he became Java developer working in the area of SmartCards and Security. Since 2007 Iliyan is fully devoted to JavaScript and Front-End development. He is highly interested in Server-side JavaScript (NodeJS), Networking and real time data processing. Performance obsessed.

**Comment by alexfernandez** [comment]
Hi, sounds like an advanced talk. We will probably schedule it for April, and will let you know with some weeks in advance. One thing: the talk is in English, right? Cool! We need more of those :)

**Comment by ipeychev** [comment]
April is even better, and please, let's schedule it after April, 15.

Yes, it will be in English. I can speak more or less Spanish, but for technical stuff, I prefer English.

Thanks,

**Comment by alexfernandez** [comment]
Hi Iliyan,

I am going to propose April 30th for this talk. Can you send me your email address to alexfernandeznpm@gmail.com?

Thanks!
