### ISSUE TITLE
fer torrez

### ISSUE THREAD

**Issue by fer1010** [madridjs/talks#40]
# Title / Título

# Description / Descripción

# Speaker Bio / Bio del Ponente

# Level / Nivel

(Beginner, Intermediate, Advanced)
(Iniciación, Intermedio, Avanzado)

# Duration / Duración

(30 min to one hour)
(30 minutos a una hora)

**Comment by alexfernandez** [comment]
Falta la charla. Completa y reabre cuando esté. Gracias.
