### ISSUE TITLE
Crear una API completa con NestJs

### ISSUE THREAD

**Issue by xavism** [madridjs/talks#41]
# Crear una API completa con NestJs

# Descripción 
Todo el mundo conoce la potencia de Node en la situación actual, y teniendo en cuenta la tendencia de uso de Javascript en las aplicaciones modernas, crear un API con Node es una de las elecciones preferidas por los desarrolladores. 
Aun así, quien haya escogido esta opción, ha podido comprobar que aun hay un tema pendiente de resolver: La arquitectura.

A principios de 2017 se creo NestJs, un framework de Nodejs que posibilita a los amantes tanto de Javascript como de Typescript a crear applicaciones de servidor eficientes y escalables de manera sencilla.

En esta charla, me gustaría enseñar como generar un CRUD de manera sencilla, e ir añadiendo funcionalidades que nos da este potente framework.

# Bio del Ponente

Mi nombre es Xavi Sánchez Mir, Fullstack developer en Tokiota.
Graduado en ingeniería informática en la universidad politécnica de Cataluña y actualmente finalizando un master en ingeniería Web en la politécnica de Madrid.
Amante de la tecnología, con pasión al transferir los conocimientos aprendidos en mis años como desarrollador

# Nivel
Esta charla empieza con un nivel sencillo para gente que se inicia en aplicaciones de servidor con Node, y se puede llegar a hacer cosas un poco mas complejas a nivel intermedio a medida que avanza la charla

# Duración

30 minutos a una hora

**Comment by alexfernandez** [comment]
Buenas, @xavism, ¿te viene bien hacer la charla a finales de abril?

**Comment by xavism** [comment]
Hola buenas, doy charlas el 19, 23 y 25 (abril). A partir del 20 estoy en
madrid, que día sería?

Si no coincide con esos, encantado!

**Comment by alexfernandez** [comment]
El 26 tenemos Node.js Madrid, ¿el 24 es posible? Lo siento si te achuchamos demasiado, lo podemos dejar para primeros de mayo también :smile:

**Comment by xavism** [comment]
Si va bien principios de mayo mejor, pero el 24 también sería posible.
☺️

**Comment by alexfernandez** [comment]
Hecho: https://www.meetup.com/es-ES/madridjs/events/249699610/.
