### ISSUE TITLE
Desarrollando componentes en un entorno aislado

### ISSUE THREAD

**Issue by zamarrowski** [madridjs/talks#42]
# Desarrollando componentes en un entorno aislado

# Description / Descripción

En la charla veremos como desarrollar componentes en entorno aislado y a su vez tener un sitio donde poder ver todos los componentes de nuestra aplicación. Usaremos Storybook y aunque podemos usar Storybook con React, React Native, Angular y Vue lo usaremos con React. Veremos sus ventajas, como configurarlo, agregar historias y generar un html para poder consultar los componentes de nuestra aplicación en cualquier momento.

# Speaker Bio / Bio del Ponente

Sergio Zamarrowski

Javascript Developer que trabaja en I4S una empresa de seguridad informática. He tenido la suerte de desarrollarme en múltiples ámbitos pero (casi) siempre usando Javascript. Soy experto en desarrollar proyectos personales sin ningún futuro pero de los cuales he aprendido muchísimo.

# Level / Nivel

Intermedio

# Duration / Duración

40 minutos

**Comment by alexfernandez** [comment]
¡Buenas, @zamarrowski! Buscamos ponente para febrero, ¿estarías disponible? Se trata de un Meetup conjunto con Cabify, en el que tendríamos sólo 25 minutos. Si se te queda corto no hay problema, eres el siguiente en la cola así que te tocará dentro de poco en cualquier caso :)

**Comment by zamarrowski** [comment]
Hola!

Pues podría ajustar el tiempo. Por otro lado en febrero tendría disponible los dias entre el 11 y el 21 de Febrero. ¿Que día sería?

**Comment by alexfernandez** [comment]
Pues perfecto porque sería el 13 de febrero. ¿Me escribes a alexfernandeznpm@gmail.com y te pongo en contacto con los organizadores?

**Comment by zamarrowski** [comment]
Perfecto!

**Comment by alexfernandez** [comment]
[Hecho](https://www.meetup.com/es-ES/madridjs/events/258528255/).
