### ISSUE TITLE
Workshop de contribución al proyecto Mattermost

### ISSUE THREAD

**Issue by jespino** [madridjs/talks#44]
# Title / Título
Mattermost contribution workshop / Workshop de contribución al proyecto Mattermost

# Link to the Meetup
https://www.meetup.com/es-ES/Mattermost-Madrid/events/248606169/

# Description / Descripción
Mattermost is an Open Source alternative to chats like Slack or Hipchat. We'll begin the workshop with a short introduction about the architecture of Mattermost code, how to setup the development environment and what types of integrations we can develop.

After the introduction, each one will decide how to contribute, directly to the project, or implementing any kind of integration (webhooks, slash commands, plugins, application using the API).

The main technologies used in the project are: javascript, react, redux, react native and golang.

/

Mattermost es una alternativa Open Source a chats como Slack o HipChat. Empezaremos el taller con una breve introducción sobre como esta estructurado el código de Mattermost, como montar el entorno de desarrollo y que tipo de integraciones podemos desarrollar.

Tras la introducción cada uno podrá decidir si quiere contribuir directamente al proyecto, o implementar algún tipo de integracion (webhooks, slash commands, plugins, applicacion usando la API).

Las principales tecnologías utilizadas en el proyecto son : javascript, react, redux, react native y golang.

# Speaker Bio / Bio del Ponente

We'll be 3 Mattermost core commiters. Jesús Espino (Mattermost Developer), George Goldberg (Mattermost Developer) and Carlos Panato (CoreOS developer).

/

Estaremos 3 core commiters de Mattermos. Jesús Espino (Desarrollador en Mattermost), George Goldberg  (Desarrollador en Mattermost) y Carlos Panato  (Desarrollador en CoreOS).

# Level / Nivel

(Beginner, Intermediate, Advanced)
(Iniciación, Intermedio, Avanzado)

# Duration / Duración

(8 hours)
(8 horas)

**Comment by alexfernandez** [comment]
Muy interesante. ¿Queréis que hagamos un evento conjunto (anunciado en ambos Meetups), o que publicitemos el vuestro? Si es lo segundo, creo que basta con enviar un mensaje a la lista de correo.

**Comment by jespino** [comment]
En principio yo había pensado en publicitarlo dentro de MadridJS, pero para mi no es un problema que el evento sea conjunto, de hecho, tiene todo el sentido. Es un evento en Madrid, tiene mucha relación con JS y que el evento sea conjunto creo que solo suma (por lo menos en nuestro lado).

Tendría que confirmarlo para darte un "si" al 100%, pero diría que podemos pensar que la respuesta es un si.

**Comment by alexfernandez** [comment]
¡Estupendo!

Hacer el evento conjunto implica crear un Meetup en MadridJS, y presentar ambas comunidades. Idealmente iríamos algún organizador de MadridJS, aunque en otras ocasiones no hemos podido.

En MadridJS no tenemos [reserva de plazas](http://pinchito.es/2016/event-attendance.html), ¿vosotros? Si no es así es más fácil porque no tenemos que hacer componendas.

**Comment by jespino** [comment]
Me comentan que podemos hacerlo perfectamente de forma conjunta, así que por mi adelante.

Respecto al numero de plazas, en realidad dependemos del espacio disponible, yo la verdad es que no he estado todavía en las oficinas de Source{d}, así que no puedo decir exactamente cuantas personas podrían entrar, pero entiendo que hay un aforo limitado. Por otro lado, vamos a ser 3 core developers, lo que significa que tampoco podremos ayudar a infinita gente.

Creo que seria bueno poner un tope en cualquier caso. Ahora mismo tenemos puesto un limite de 25 personas. Y preguntamos a la gente cuando se apunta la talla de camiseta, porque queremos encargar algo de Swag para el evento.

**Comment by alexfernandez** [comment]
Pues en ese caso decidme cuántas plazas ponemos nosotros. En nuestra experiencia suele ir del 30 al 50% de la gente apuntada, por si os sirve de ayuda. No hay problema en preguntar la talla de camiseta (pero contad con que muchos de los que se apunten no van a ir).

**Comment by jespino** [comment]
Estoy confirmando el numero de plazas con Alex de Source{d}, pero podeis ir anunciando el meetup y poniendo un limite de 25, por ejemplo, y veamos que pasa :)

**Comment by alexfernandez** [comment]
¡Publicado! Intentaremos pasarnos por allí.

**Comment by alexfernandez** [comment]
Hecho, ¡gracias! https://www.meetup.com/es-ES/madridjs/events/249167260/
