### ISSUE TITLE
Introducción a Angular

### ISSUE THREAD

**Issue by pjmolina** [madridjs/talks#45]
# Title / Título
Introducción a Angular

# Link to the Meetup
https://www.meetup.com/es-ES/madridjs/events/249700071/

# Description / Descripción
Angular se ha convertido por pleno derecho en un reconocido framework moderno y completo para la creación de aplicaciones SPA.
En esta charla revisaremos sus conceptos fundamentales describiendo su arquitectura, el patrón SPA, TypeScript así como las herramientas involucradas en el desarrollo.

La charla está orientada sobre todo a desarrolladores con conocimientos de desarrollo web clásico (ASP NET, Java, Ruby, PHP) que quieran dar sus primeros pasos con Angular y TypeScript.

# Speaker Bio / Bio del Ponente
Pedro J. Molina.

Doctor en Informática. Desde Metadev, desarrolla software, tutoriza y forma equipos de desarrollo en tecnologías y practicas de ingeniería software. Twitter [@pmolinam](https://twitter.com/pmolinam) | Linkedin https://www.linkedin.com/in/pjmolina

# Level / Nivel
Intermedio

# Duration / Duración
90 minutos

**Comment by alexfernandez** [comment]
Hecho: https://www.meetup.com/es-ES/madridjs/events/249700071/
