### ISSUE TITLE
PREACT - The quest for the 50kb app

### ISSUE THREAD

**Issue by Ruivilela** [madridjs/talks#46]
# Title / Título
PREACT - The quest for 50kb app
# Description / Descripción
Preact is a react based library but with 3kb. In this talk I'm going to talk the difference between react and Preact and it's use cases. Also how does preact work in the context of Redux.
 In the end, I'll demonstrate preact with a project that I made. 

The purpose of this talk, is to get people to know the technology and see more people using it. 

# Speaker Bio / Bio del Ponente
I'm a Business guy that had is own company, but suddenly became a programer a year and half ago. Did the ironHack bootcamp in Madrid, where I learnt to program in ruby, but quickly got fascinated by the Front end World, and never got back to Ruby. Currently I'm working for Beamery a company based in London where I'm a Front end Developer, but have worked on many other projects in Portugal, Spain and in the Netherlands. 

# Level / Nivel
Intermediate - Advance, you have to understand react to understand preact. Understanding redux is plus although it's not necessary. 

(Beginner, Intermediate, Advanced)
(Iniciación, Intermedio, Avanzado)

# Duration / Duración
30min - 1 hour

(30 min to one hour)
(30 minutos a una hora)

**Comment by alexfernandez** [comment]
Buenas, ¿estás disponible para hacer la charla a finales de mes?

**Comment by alexfernandez** [comment]
Hi, are you available at the end of this month?

**Comment by manufosela** [comment]
Hi, are you available at the end of this month or next month?
