### ISSUE TITLE
Aplicando principios SOLID en Javascript gracias a Typescript

### ISSUE THREAD

**Issue by leomicheloni** [madridjs/talks#47]
# Aplicando principios SOLID en Javascript gracias a Typescript

# Descripción

Se ha hablado mucho sobre los principios SOLID sin embargo nunca es tarde para recordarlos, su importancia para que una aplicación sea mantenible, flexible y evolutiva son bien conocidos y es definitivamente una de las herramientas que debemos tener en nuestro arsenal. Si bien estos principios han sido pensados para aplicarlos en lenguajes orientados a objetos es posible usar muchas de sus ideas en Javascript cualquier sea su versión. Gracias a las capacidad que Typescript suma a Javascript podemos aplicarlos al 100%. En esta charla vamos a hacer un repaso de los principios SOLID, por qué son importantes y veremos con ejemplos su aplicación en nuestras aplicaciones utilizando Typescript.

# Bio del Ponente

 Soy Argentino y vivo en España desde 2017 y actualmente trabajo en Tokiota Madrid. Comencé en la programación cuando trabaja en electrónica comenzando con el assembler puro y duro para después pasar a lenguajes de alto nivel; me he dedicado a programar desde entonces y desde esto ya han pasado más de 15 años.
 Me interesan los temas relacionados con las buenas prácticas y arquitectura del software y cómo ser un mejor programador cada día.
 He trabajado en diferentes tipos de proyectos y he tenido la suerte de compartir con grandes profesionales de los que he aprendido mucho. He sido reconocido como Microsoft MVP los últimos tres años por mi aporte a la comunidad Javascript de Latam.

# Nivel

Beginner / Intermediate

# Duración

45 minutos

**Comment by alexfernandez** [comment]
[Hecho](https://www.meetup.com/es-ES/madridjs/events/258700807/).
