### ISSUE TITLE
De idea a clientes

### ISSUE THREAD

**Issue by rickitan** [madridjs/talks#48]
# Title / Título

De idea a clientes

# Description / Descripción

El talk trata sobre todo el proceso de ir de una idea hasta tener un producto con clientes. Voy a cubrir todas las etapas, obstáculos, lucha creativa y cómo mantener la motivación.

El talk va a estar basado en mi experiencia creando [Appdelante](https://appdelante.com). Un proyecto en el que llevo más de dos años desarrollando. Algunos de los puntos:

- Que tecnologías utilizar
- Cómo mantener el momentum
- El poder de ser un indie developer (no tener financiamiento)
- Cómo cambiar el curso sobre la marcha
- Cómo mantener los costos virtualmente en cero
- Todas estas ideas las estoy usando para está serie de Youtube: https://www.youtube.com/watch?v=its05y9XBZk
- Y más.

# Speaker Bio / Bio del Ponente

Soy un ingeniero de software y llevo más de 5 años trabajando con JavaScript y Node.js.

Nací, crecí y estudie en Venezuela. Después de graduarme comencé a trabajar para [Canvs.tv](http://canvs.tv/) ubicada en NYC. Fui uno de los primeros 5 ingenieros y ayude a desarrollar una plataforma que le permite a HBO, Showtime, Fox y más, entender cómo su audiencia reacciona en las redes sociales cuando un episodio o programa sale al aire.

Luego, me uní a [AppDirect](https://www.appdirect.com/) ubicada en San Francisco y ayude a lanzar la aplicación de visualización de datos AppInsights que le permite a cualquier compañía integrar sus métricas en un mismo sitio.

Actualmente, trabajó en [Shopify](https://www.shopify.com/) desarrollando herramientas que le permite a los usuarios crear el branding de sus tiendas virtuales.

# Level / Nivel

Iniciación

# Duration / Duración

30 minutos

**Comment by alexfernandez** [comment]
Hecho, ¡gracias! https://www.meetup.com/es-ES/madridjs/events/251189071/
