### ISSUE TITLE
Nuevas APIs del W3C: qué hay en el horno

### ISSUE THREAD

**Issue by tripu** [madridjs/talks#49]
## Descripción

La web no nació con Twitter, y ni siquiera con Myspace. La triple uve doble tiene casi tres décadas de vida. Y durante los últimos 24 años, el [World Wide Web Consortium (W3C)](https://www.w3c.es/) ha sido el principal organismo responsable de impulsar su desarrollo. El catálogo de estándares y documentación que el W3C coordina y mantiene hace que hoy podamos mantener una videoconferencia, jugar en tiempo real y maquetar periódicos digitales en árabe&hellip; todo sin salir de un navegador. Y lo que es más importante: manteniendo principios de neutralidad tecnológica, estándares abiertos y el consenso de la comunidad. El W3C no tiene ánimo de lucro, y publica su trabajo gratis, y libre de patentes.

Las últimas APIs JS ([*Media Capture*](https://www.w3.org/TR/html-media-capture/), [*Indexed Database 2.0*](https://www.w3.org/TR/IndexedDB-2/), [*Web Cryptography*](https://www.w3.org/TR/WebCryptoAPI/), por nombrar algunas), la velocidad con que los navegadores las implementan, y los dispositivos ubicuos están creando un sustrato extremadamente fértil para la programación de verdaderas aplicaciones.

En esta charla haríamos un repaso de [algunas de las APIs más recientes](https://www.w3.org/TR/?tag=webapi&status=wd&version=ed): las publicadas en los últimos meses, y también las que se encuentran en un estadio temprano aún. Mencionaríamos APIs que vienen y que merece la pena conocer. Algunos ejemplos de lo que ahora empezamos a poder hacer (o de lo que nos depara el futuro próximo):

* Controlar nuestro juego HTML5 [con un *gamepad*](https://www.w3.org/TR/gamepad/)
* Explotar el [rendimiento de WebAssembly](https://www.w3.org/TR/wasm-core-1/) para aplicaciones científicas y para 3D
* Acceder con menos fricción al [sistema de archivos](https://www.w3.org/TR/FileAPI/), al [portapapeles](https://www.w3.org/TR/clipboard-apis/) y a [capturas de pantalla](https://www.w3.org/TR/screen-capture/) (para mejorar aplicaciones de videoconferencia, edición gráfica, ofimática)
* Delegar la [gestión de nuestros pagos *online*](https://www.w3.org/TR/payment-handler/) a terceras partes de confianza de forma segura
* Autenticarnos en sitios web [sin usar contraseñas](https://www.w3.org/TR/webauthn/)

Finalmente, explicaríamos brevemente cómo aprovechar las herramientas, servicios y recursos que el W3C pone a disposición de profesionales y estudiantes, gratis.

## Bio del ponente

Nacido en Madrid en 1980. Ingeniero en informática por la Universidad de Granada.

Durante los últimos 15 años ha trabajado como programador, analista y jefe de proyectos; tanto en *start-ups* como en empresas multinacionales; en Sevilla, en Madrid, en Londres y en Tokio. Sus principales intereses son el *software* libre, GNU/Linux, los sistemas abiertos, la informática gráfica, interfaces y usabilidad, la tecnología de la web y JavaScript.

Actualmente vive en Madrid, y es [programador web](https://www.w3.org/People/#antonio) dentro del [equipo de sistemas del W3C](https://www.w3.org/People/functions/systeam) desde 2014. Entre otras cosas, se dedica a desarrollar herramientas y aplicaciones del W3C, públicas o internas; y a participar en eventos relacionados con los estándares web.

## Nivel

**Intermedio** porque hablaríamos de APIs JS y funcionalidades de los navegadores que son bastante recientes (o incluso no oficiales todavía), y que seguramente no conocerán muchos principiantes. Pero no pretendo mostrar código más que en algunos ejemplos muy simples, así que debería ser comprensible para casi todos.

## Duración

**30&prime;&ndash;40&prime;** de presentación con ejemplos, seguido de **5&ndash;15&prime;** para preguntas, comentarios, compartir experiencias personales&hellip;

---

NB: la charla y la presentación podrían ser en español, o en inglés (lo que el grupo prefiera).

**Comment by tripu** [comment]
@alexfernandez, ¿habéis visto mi propuesta? :)

**Comment by alexfernandez** [comment]
Buenas, claro que la hemos visto. Salvo que haya algún tipo de prioridad solemos ir por orden de entrada, ¿preferís hacerlo en alguna fecha concreta?

**Comment by tripu** [comment]
Ah, OK. Solo quería asegurarme, porque no veía ninguna reacción :)

No tengo preferencias de fechas, y me parece bien si la costumbre es ir por orden. Con que me aviséis dos o tres semanas antes de que &laquo;me toque&raquo; para confirmar todo, por mí bien.

**Comment by alexfernandez** [comment]
¡Por supuesto! Te avisaremos con tiempo, y si en cualquier momento tienes algún condicionante (por ejemplo, que quieras practicar la charla antes de darla en alguna conf), dinos y te acomodamos :)

**Comment by alexfernandez** [comment]
Buenas, ¿podrías a finales de este mes? Por ir buscando sitio.

**Comment by tripu** [comment]
@alexfernandez,
precisamente estoy un poco peor de tiempo últimamente (he cambiado de trabajo hace tres meses y ya no estoy en el W3C).
Preferiría postponer esta charla hasta que pueda prepararla bien otra vez&hellip;
¡Gracias!

**Comment by alexfernandez** [comment]
Vale, pues avisa cuando puedas, ¿vale?

**Comment by tripu** [comment]
@alexfernandez: han pasado unos meses, ya no trabajo en el W3C, y estoy menos al día de las APIs que están cocinándose ahora mismo. En cambio, ahora podría dar esta otra charla (#63) fácilmente.

Por mí, cerramos esta, y si os parece, programamos la otra. ¿Qué opinas? Perdonad la confusión.

**Comment by alexfernandez** [comment]
¡Me parece estupendo!
