### ISSUE TITLE
Creating Web Applications with ReactJS and Flux

### ISSUE THREAD

**Issue by ipeychev** [madridjs/talks#5]
Description:
ReactJS is a JavaScript library for creating user interfaces with primary focus on performance. Flux is an application architecture, which plays nice with ReactJS. Both of them are used by Facebook in production.
In the talk we will dive into both of them and give some practical examples.

Bio:
Iliyan Peychev is a Software Engineer and UI Infrastructure Lead in Liferay Inc. He started as C developer fourteen years ago, when he was writing software for banks and other financial institutions. Then he became Java developer working in the area of SmartCards and Security. Since 2007 Iliyan is fully devoted to JavaScript and Front-End development. He is highly interested in Server-side JavaScript (NodeJS), Networking and real time data processing. Performance obsessed.

**Comment by alexfernandez** [comment]
Schedule pending.

**Comment by luispablo** [comment]
+1 for this talk. Maybe some real life expriencies could be included...? ;)

**Comment by ipeychev** [comment]
There will be an example for ReactJS applied to existing project. Not only that, but I will describe how this project was achieved before React and we will compare both approaches.

**Comment by alexfernandez** [comment]
Initially scheduled for June, although it may change.

**Comment by alexfernandez** [comment]
Time to schedule talks for September, is Thursday 24th a good date for you?

**Comment by ipeychev** [comment]
Hey Alex,

For some reasons, I think I won't be able to give this talk. However, I think a colleague of me, @jbalsas will be able to do it. He is from Spain, so the talk can be in Spanish.
Chema, are you OK with this?

**Comment by jbalsas** [comment]
Hey guys, sure, no problem!

I think Thursday 24th should be just fine if that's ok with Alex :)

**Comment by alexfernandez** [comment]
That is brilliant! 19:00 at impact hub, I will create the Meetup soon. @jbalsas, be sure to register there so that I can add you as speaker: http://www.meetup.com/es/madridjs/

**Comment by jbalsas** [comment]
Hey @alexfernandez, I've been registered for quite a while (http://www.meetup.com/es/madridjs/members/74054132/). Feel free to go ahead with the schedule ;)

**Comment by alexfernandez** [comment]
@jbalsas: can you provide a bio for the meetup? As a comment so that I get notified, thanks!

**Comment by jbalsas** [comment]
Hey @alexfernandez...

Short BIO: _Telecommunications Engineer by Universitat Politècnica de València, Chema was involved in network-related research at Fraunhofer FOKUS Berlin & developed multimedia apps for Prisa Group Madrid. Working as Software Engineer for Liferay since 2013, he focuses mainly in Front-end development and AlloyEditor._

Also... could we update the title? I'm wondering if we'd show `Flux` at all, and maybe it would be good to include that we'll show a real life example and the name, so the guys know what to expect and can research beforehand if they are interested. Thoughts on this, @ipeychev?

**Comment by alexfernandez** [comment]
Sure, [updated](http://www.meetup.com/es/madridjs/events/225252829/). By the way, 140 people are attending already! :clap: If you want you may update the description here and let me know. You can even translate description and bio to Spanish if the talk is going to be in Spanish.

**Comment by jbalsas** [comment]
Oh, that's right, I didn't realize... I'll update and translate both and ping you here asap :wink:

**Comment by jbalsas** [comment]
Hola @alexfernandez ,

Te copio el título y descripción de la charla actualizados y mi bio en español.

**Título**
_React en la vida real: AlloyEditor_

**Descripción**
_React es una librería JavaScript pensada para crear interfaces de usuario con un gran rendimiento. React propone un cambio radical en la manera en la que construimos UI: empezando por redefinir la manera en la que organizamos nuestros componentes y terminando por modificar el flujo de datos que se establece entre ellos. Con esta nueva visión, a veces enfrentada al orden establecido, hacer componentes reutilizables y testeables con los que desarrollar nuestras aplicaciones se vuelve más fácil y confiable que nunca._

_En esta charla, superpondremos los conceptos teóricos en los que se basa el framework con una implementación práctica en la vida Real: AlloyEditor, un editor WYSIWYG cuya interfaz está construida en React._

**Bio**
_Ingeniero de Telecomunicaciones por la Universitat Politècnica de València. Chema estuvo involucrado en investigación de redes en el Fraunhofer FOKUS de Berlín y ha desarrollado aplicaciones multimedia para el Grupo Prisa. Trabaja como Ingeniero de Software para Liferay desde 2013 y se centra principalmente en el desarrollo de infraestructura de FrontEnd y AlloyEditor._

**Comment by jbalsas** [comment]
@alexfernandez, ¿a qué hora empezaría la charla y de qué duración estamos hablando? :wink:

**Comment by alexfernandez** [comment]
jbalsas: ¡Actualizado! El meetup empieza a las 19:00 y cada charla debería durar alrededor de media hora. Tenemos que dejar la sala a las 20:30. Así que pongamos que la tuya, que va la segunda, debería empezar alrededor de las 19:45, contando 5 minutos de preguntas y 10 para el cambio de ponente.

**Comment by alexfernandez** [comment]
Actualizado de nuevo: una única charla que empieza a las 19:00 y dura 45 minutos + 15 de preguntas.

**Comment by jbalsas** [comment]
:+1:

**Comment by jbalsas** [comment]
@alexfernandez, he subido las transparencias a la web del grupo. Puedes encontrarlo [aquí](http://files.meetup.com/2301351/React%20en%20la%20Vida%20Real%20-%20AlloyEditor.pdf), aunque ahora que veo el link, quizá deberíamos renombrar el fichero :joy:

**Comment by alexfernandez** [comment]
Perfecto, ¿tienes el enlace al repo?

**Comment by jbalsas** [comment]
Está en la última transparencia. La rama con la demo es:

https://github.com/jbalsas/alloy-editor/tree/madridjs-2015
