### ISSUE TITLE
Vue.js in production

### ISSUE THREAD

**Issue by ndemengel** [madridjs/talks#50]
# Title / Título

Vue.js in production

# Description / Descripción

This is our return on experience about using Vue.js to build applications at [Malt](https://www.malt.es).

Specifically, we'd like to cover the following subjects:
- why we chose to use Vue in the first place
- how we integrated our existing internationalization stack with it, why we didn't use Vue I18n
- how we built HATEOAS resources in such a way that Vue components are mostly unaware of the API structure
- how we started building a common base that all our Vue applications can leverage
- how we monitor our front-end in production (logging, alerting)

We've started using Vue one year ago, and we're currently building our third application with it.

# Speaker Bio / Bio del Ponente

After 1 year at the radio and 1 year as a video teacher, Pierre have decided to become a front-end developer 3 years ago. What a great move!
Nicolas have been developing applications using JavaScript and Java for a decade.
Since 2015, Pierre and Nicolas are breaking their voice at Malt's karaoke sessions.

# Level / Nivel

Intermediate

# Duration / Duración

Approximately 45 minutes

# Constraints / Condicionantes

We aim to spend some days in Madrid in mid-October; we propose to use that time to give our talk.

**Comment by alexfernandez** [comment]
Let me know when you have the dates closed so we can book a space.

**Comment by alexfernandez** [comment]
[Done](https://www.meetup.com/es-ES/madridjs/events/255232022/), thanks!
