### ISSUE TITLE
Node.js & React Native

### ISSUE THREAD

**Issue by jordiperezdelolmo** [madridjs/talks#51]
# Title / Título
Node.js & React Native

# Description / Descripción
If you're a web developer who has been itching to get into native development, now is your chance. In this series we'll be talking all about React Native and Node.js. React Native allows you to build native iOS and Android applications in JavaScript, and React.js. Node.js allows you to create servers to communicate with your app to provide a better experience inside the app.

# Speaker Bio / Bio del Ponente
Italo Brito Brasil - Fullstack Developer with more then 10 years working with web technologies and many systems and apps in Brazil. Design Thinker and Leader of IxDA Teresina, BeerJS & @21unicorns.

Evangelist JS & React Native where i teach about new approaches to create nice apps with great UIs and with a good expe
[iesede-flyer.pdf](https://github.com/madridjs/talks/files/2451264/iesede-flyer.pdf)
rience too.

# Level / Nivel
Intermediate

# Duration / Duración
 one hour

# Constraints / Condicionantes
October, November

**Comment by alexfernandez** [comment]
Closing after talking to @jordiperezdelolmo, please reopen when necessary.
