### ISSUE TITLE
How to effectively test your React/Vue application

### ISSUE THREAD

**Issue by maxpou** [madridjs/talks#53]
# Title / Título

How to effectively test your React/Vue application

# Description / Descripción

Testing is very important. But depending on how you write them, it can speed you up or slow your development. Knowing how to write proper and relevant test is essential.
During this session, we will cover:
* what we need to test and what we don't need to test;
* how to use snapshot testing;
* how to test components.

I will also give you some tips to write better tests and avoid common pitfalls!

# Speaker Bio / Bio del Ponente

For the last decade, Maxence Poutord ([@_maxpou](https://twitter.com/_maxpou)) has worked with a variety of web technologies. He is currently focused on front-end development. On his day to day job, he is working as a senior front-end engineer at VSware. He is also a frequent tech speaker and a mentor. As a new digital nomad, he is living where the WIFI and sun is 😎 

https://www.maxpou.fr

# Level / Nivel

Intermediate

# Duration / Duración

45 minutes (without Q/A)

# Constraints / Condicionantes

**I'm in Madrid from 7/11 to 3/12**

**Comment by maxpou** [comment]
Thanks for having me :)

**Comment by alexfernandez** [comment]
Thanks a lot, @maxpou ^_^
