### ISSUE TITLE
Workshop de introducción a JS (de ES6 pa' lante)

### ISSUE THREAD

**Issue by ardiadrianadri** [madridjs/talks#55]
# Title / Título
Introducción JS (de ES6 pa' lante)
# Description / Descripción
JavaScript es uno de los lenguajes más versátil que existe hoy en día.  Te sirve tanto para programar web, como para crear servidores en el back, como para controlar placas de dispositivos. Pero antes de lanzarnos a crear algo tan complejo como sistemas de control para [condensadores de fluzo](https://es.wikipedia.org/wiki/Condensador_de_flujo) es bueno tener claro cuales son los bases del lenguaje. 
* Cuales son los tipos básicos
* Que operaciones se pueden realizar por cada tipo
* Que es una variable
* Cuales son las estructuras de control de JS

Este workshop va dirigido a todas aquellas personas que están pensando en introducirse por primera vez en el mundo de la programación en JS con ES6. Sé empezará con el concepto de sentencias y se intentará llegar a la definición de "clases". Si siempre has tenido curiosidad de aprender JS este esta es tu oportunidad de empezar con buen pie.

# Speaker Bio / Bio del Ponente
Nosotros somos la guild de Ideas de OSW. Es decir, un grupo de personas que pertenecen al Meetup de OSW y que nos reunimos para hacer Open Software. Sin embargo no somos personas cualquiera; la mayor parte de los componentes del guild de Ideas llevamos menos de tres meses programando y no somos profesionales dentro del mundo de la informática. A pesar de eso, con esfuerzo, nos dedicamos a leer, estudiar y aprender de todos los recursos que encontramos en la web y, aquello que hemos aprendido, queremos compartirlo con los demás. Esta claro que no somos expertos pero en ganas y voluntad poco nos superan. Es por eso que este workshop va dirigido a todas aquellas personas que al igual que nosotros han empezado hace poco en el mundo del desarrollo de software y quieren aprender con nosotros.

### Silvia Arnaiz
Soy Silvia, politóloga, administrativa, contable, y actualmente desarrolladora. Durante toda mi carrera profesional he aprendido que lo único para lo que hay que estar realmente preparado es para el cambio y por eso he iniciado este nuevo viaje que espero me lleve a formar parte de las comunidades de Open Software.

### Fabiola Vieyra
Ex-bailarina y profesora. Estudié la Licenciatura en Enseñanza de la Danza en el Instituto Nacional de Bellas Artes de la Ciudad de México de donde soy originaria. Conocí la programación gracias a Free Code Camp y gracias a ello soy apasionada de JavaScript. El verano de 2017 gané una beca de Woman Techmakers y Udacity para cursar su nanodegree de desarrollo front-end. Actualmente curso el Master de desarrollo full stack.

# Level / Nivel
Iniciacion
(Beginner, Intermediate, Advanced)
(Iniciación, Intermedio, Avanzado)

# Duration / Duración
4h
(30 min to one hour)
(30 minutos a una hora)

# Constraints / Condicionantes
Tener instalada la última version LTS de NodeJS
(Any constraints you have, e.g. specific dates)
(Condicionantes, por ejemplo una fecha específica)

**Comment by alexfernandez** [comment]
¡A tope! Lo publicamos ya mismo si te parece.

**Comment by ardiadrianadri** [comment]
Si Alex. Publicarlo cuando queráis

**Comment by alexfernandez** [comment]
¿A qué hora empezará, @ardiadrianadri ? Liferay castellana, ¿no?

**Comment by ardiadrianadri** [comment]
Perdona @alexfernandez.
Si Liferay es ahí, en la castellana, en frente de las 4 torres y al lado del VIPS ( [Paseo de la Castellana, 280, 28046 Madrid](https://goo.gl/maps/YuUhXwvYoL72)). El workshop empieza a las 10:00 y termina a las 14:00. 4 horas de puro JS.

**Comment by alexfernandez** [comment]
Cool! Publicado, @ardiadrianadri: te he hecho administrador de evento así que cualquier cambio ya sabes. ¡Muchas gracias por organizar!
