### ISSUE TITLE
Introduction to service workers - Talk in english

### ISSUE THREAD

**Issue by marabesi** [madridjs/talks#56]
# Title / Título
Introduction to service workers

# Description / Descripción

Obs: talk in english

Service workers were born to improve the user experience in the connectivity aspect.

In the offline, which is the case when the user has no connection at all to the 
internet and the lie-fi, which is a term related to low(for instance 2G) connection and high latency.

The first part of the talk is going through the basics of service worker, as:

- What it is
- Why should you use it
- Introduction to the service worker API/ cache API
- Javascript code examples

 
The second part is focused on giving a real world example, in scenarios that service workers can be applied.

# Speaker Bio / Bio del Ponente

Marabesi is addicted to software development, best practices, design patterns and testable code. Besides the professional projects, he has been researching about software testing and gamification.

# Level / Nivel

(Beginner)

# Duration / Duración

40 min to one hour

# Constraints / Condicionantes

N/A

**Comment by alexfernandez** [comment]
@marabesi Can you do the talk at the end of this month?

**Comment by marabesi** [comment]
@alexfernandez this month I can't unfortunately, is it possible to arrange it next month (around 15 ~ 20)?

**Comment by alexfernandez** [comment]
Sure! What date works best for you?

**Comment by marabesi** [comment]
15/05 works for me

**Comment by alexfernandez** [comment]
Does the 14th work for you too? We have another speaker that can do it on that date, so we can do both if it suits you!

**Comment by marabesi** [comment]
Sure, the 14th is fine 👍

**Comment by alexfernandez** [comment]
Cool! I will start looking for a venue :smile_cat:

**Comment by alexfernandez** [comment]
Can you please write to me to alexfernandeznpm@gmail.com so I can include you in any mails pertaining the talk? Thanks!

**Comment by marabesi** [comment]
done

**Comment by alexfernandez** [comment]
[Done](https://www.meetup.com/es-ES/madridjs/events/261046807/).
