### ISSUE TITLE
Define y Desarrolla Tu Primera Skill para Google Home

### ISSUE THREAD

**Issue by jesuscuesta** [madridjs/talks#57]
# Title / Título
Define y Desarrolla Tu Primera Skill para Google Home

# Description / Descripción
A finales del año pasado, terminaron de hacer su desembarco más tipos de dispositivos con los que manejar nuestra Smart House. ¿Serías capaz de desarrollar una skill para tu asistente virtual? En una hora, tendrás tu prototipo montado.

En los anteriores años, se han vendido millones de dispositivos alrededor del mundo, y ahora es el turno de España. A pesar de que algunos de ellos solo están en inglés, podemos desarrollar y publicar nuestras skills en su marketplace. En estos momentos nos podemos encontrar diferentes dispositivos con asistentes virtuales, desde los típicos como Google Home, Alexa Amazon, Homepod de Apple... a otros que utilizan estos por debajo como los de Sonos o Lenovo.

¿Pero qué perfiles son necesarios para diseñar y desarrollar una skill de voz? ¿qué tecnologías utiliza por debajo? ¿puedo yo solo desarrollarla?

Nos centraremos en desarrollar una aplicación sencilla para Google Home, y definiremos la estructura e infraestructura necesaria para llevarlo a cabo. Para aquellos que quieran desarrollarla en paralelo, solo necesitaréis conocimientos estándares en programación y conocimiento medio de Javascript.

# Speaker Bio / Bio del Ponente
Apasionado de las nuevas tecnologías, Líder Técnico del Centro de Expertos Javascript de AT Sistemas, Co-Organizador de los meetups Desarrolladores Cloud y Smart Devices, colaborador de OpenExpo Europe y Hackathon Lovers y aficionado a eventos tecnológicos, hackathones y marketing digital.

# Level / Nivel
Intermedio

# Duration / Duración
1 hora más networking posterior

# Constraints / Condicionantes
Para los que quieran desarrollar en paralelo: conocimientos de programación, conocimientos de Javascript, portátil

Martes 5 de Febrero de 19:30 a 20:30 en el Google Campus. Ya está aprobada la charla.

**Comment by alexfernandez** [comment]
[Hecho](https://www.meetup.com/es-ES/madridjs/events/258281093/).
