### ISSUE TITLE
Micro frontends

### ISSUE THREAD

**Issue by jorgecasar** [madridjs/talks#58]
# Title / Título

Micro frontends

# Description / Descripción

La idea detrás de Micro Frontends es pensar en un sitio web o aplicación web como una composición de características que son propiedad de equipos independientes. Hablaremos sobre técnicas, estrategias y recetas para crear una aplicación web moderna con varios equipos utilizando diferentes frameworks de JavaScript.

# Speaker Bio / Bio del Ponente

- Sergio Contreras: Arquitecto de Software en BBVA donde trabaja actualmente especializado en tecnologías JavaScript orientadas al desarrollo de arquitecturas basadas en Web Components
- Jorge del Casar: Responsable de Frontend en Citibox y GDE en Tecnologías web y Assistant.

# Level / Nivel

Intermedio

# Duration / Duración

1 hora

# Constraints / Condicionantes

Disponibilidad los martes

**Comment by alexfernandez** [comment]
Buenas, @jorgecasar, ¿qué tal lo tienes a finales de este mes?

**Comment by jorgecasar** [comment]
Pues perfecto! El 30 de abril?

**Comment by alexfernandez** [comment]
¡Vamos a por ello! Voy buscando sala.

**Comment by jorgecasar** [comment]
@alexfernandez, no había caído en que el 1 de Mayo es fiesta, lo mismo la gente hace puente. Lo pasamos a la semana siguiente? Cómo lo ves?

**Comment by alexfernandez** [comment]
Uy, es verdad, si yo mismo no voy a estar. ¡Vale! ¿7 de mayo pues?

**Comment by sergicontre** [comment]
yo no estoy esa semana en España :( 

del 13 al 22 de Mayo yo estoy free

**Comment by alexfernandez** [comment]
¿Qué día os viene bien entonces?

**Comment by jorgecasar** [comment]
El 14, que es la primera fecha en la que podemos @sergicontre y yo :D

**Comment by alexfernandez** [comment]
Perfecto, vamos reservando para el 14 de mayo.

**Comment by alexfernandez** [comment]
Vamos a hacer coincidir la charla con https://github.com/madridjs/talks/issues/56, si os parece bien. Os damos 30~45 minutos a cada uno. Además me falta el correo de @sergicontre, si me podéis escribir a alexfernandeznpm@gmail.com os pongo un correo en común explicando todo.

**Comment by alexfernandez** [comment]
[Hecho](https://www.meetup.com/es-ES/madridjs/events/261046807/).
