### ISSUE TITLE
Programar un bot en JavaScript para validar PR

### ISSUE THREAD

**Issue by ardiadrianadri** [madridjs/talks#59]
# Title / Título
DangerJS: Programar un bot en JS para validar Pull Request

# Description / Descripción
### ATENCION!!!
En esta charla no se tratan temas de machine learning ni de IA. Quedáis avisados

Posiblemente una de las tareas que más estrés o piques causa entre los miembros de un equipo es la revisiones de código. Por varias razones:

 1. La prisas: El que ha realizado el desarrollo quiere que sus cambios pasan a la rama de desarrollo cuanto antes y el que tiene que revisar la PR tiene que dejar su tarea para darle salida al cambio

2. La metodología: ¿Has escrito el titulo con el formato correcto? ¿Has añadido el código de la issue en el cuerpo del mensaje? ¿Has actualizado el change log? ¿La PR tiene las etiquetas correctas?

3. Los criterios de código: No todos los miembros del equipo tienen la misma filosofía de calidad de código. Cosas como los comentarios, el formato del nombrado de variables, el path donde se posicionan los ficheros, el nombre de los ficheros...

Para ayudarnos en este aspecto esta DangerJS. Una librería de JavaScript que permite programar scripts en NodeJS que nos pueden ayudar a controlar todos estos aspectos de la PR y más.

El objetivo de esta charla es mostrar las posibilidades de DangerJS a la hora de programar bots para el control de las Pull Request en servidor de git remotos como Github y Bitbucket 

# Speaker Bio / Bio del Ponente
Soy Adrian Ferreres y el asma, los videojuegos y Star Trek hicieron que con 11 años empezara a programar. Hoy en día, a mis 40 abriles, sigo programando en el lenguaje que más me gusta y apasiona; JavaScript. 
Encantado de compartir mi conocimiento con vosotros
# Level / Nivel
Intermedio

# Duration / Duración
1 hora

# Constraints / Condicionantes
Como de costumbre, en mis charlas, yo pongo le lugar y la fecha. Todavía no los tengo. Os lo daré después del puente del 1 de Mayo.
 
Lo único que quiero preguntaros es ¿Tenéis alguna preferencia para que esta charla se presente a partir de una fecha concreta? ... no sé... por ejemplo: "Adrian ¿puedes presentar tú charla a principios de Junio? tenemos 4 conferencias en cola y no queremos que se presentan muchas charlas muy de seguido". Ya me diréis lo que sea

**Comment by ardiadrianadri** [comment]
Hola gente:

 Ya tengo fecha definitiva. La charla será el próximo 12 de Junio a las 19:00 horas. El lugar es la sede de Sngular (Calle Labastida, 1, 28034 Madrid).

**Comment by alexfernandez** [comment]
[Hecho](https://www.meetup.com/es-ES/madridjs/events/262047907/).
