### ISSUE TITLE
Stealing from Clojure(Script)

### ISSUE THREAD

**Issue by dialelo** [madridjs/talks#6]
# Stealing from Clojure(Script)

(el material de la charla estará en inglés pero la daré en español)

## Description

In this talk we'll explore the innovation that has happened in the Clojure(Script) community
for building applications in the browser and how we can leverage such ideas and the
functional programming paradigm in JavaScript.

We'll see how virtual DOM implementations like React open up possibilities for a functional
architecture in our applications, which can be radically simpler than traditional approaches.
The main benefits are a sound separation of concerns, better reasoning about the systems we
design and the ability to easily test our applications.

The topics we'll cover include, but are not limited to:
  - Functional programming
  - State management & immutability
  - Error handling
  - Communication & coordination using Communicating Sequential Processes
  - Testing
  - Recasting Flux using all of the above

The talk will be based on a project that I'm currently working on using the aforementioned
ideas and techniques.

## Bio

Alejandro is a software developer from the Basque Country who is currently based in Madrid.
He works for Kaleidos Open Source, where he writes software in the back-end using Python and
in the front-end using JavaScript. After work he likes to hack with Clojure(Script) and Haskell
and organizes the Functional Programming Madrid meetup.

**Comment by voylinux** [comment]
+1

**Comment by keyvanakbary** [comment]
:+1: Awesome!

**Comment by joedicastro** [comment]
+1 Tu preparala aunque luego no la acepten, siempre te vendrá bien tener varias charlas en la recamara. Hay por ahí alguna "figura" internacional que se dedica a dar la mismas charlas en varios sitos. Cuantas más tengas, más oportunidades podrás aprovechar y el proceso siempre se aprende algo.

**Comment by dialelo** [comment]
@joedicastro por supuesto, tenía pensado darla en el curro para contar lo que estoy haciendo en el proyecto actual ya que creo que nos puede servir para hacer aplicaciones web más manejables. En Kaleidos hay alguno de esos rockstars que van con sus charlas "on tour" y viven de las rentas, por ejemplo @lmivan :trollface:

**Comment by manute** [comment]
+1

**Comment by eferro** [comment]
+1

**Comment by alexfernandez** [comment]
Wow! Qué aceptación. Suena a charla avanzada, obviamente :)

En principio tenemos el próximo hueco en mayo. Una pregunta, ¿la charla sería en inglés?

**Comment by dialelo** [comment]
Por mí OK a darla en mayo :)

Podría darla en español o en inglés según prefiráis aunque las slides estarán en inglés.

**Comment by alexfernandez** [comment]
A mí me da igual, supongo que en español puedes llegar a más audiencia.

**Comment by lmivan** [comment]
> En Kaleidos hay alguno de esos rockstars que van con sus charlas "on tour" y viven de las rentas, por ejemplo @lmivan :trollface:

Ehh, que yo tengo charlas nuevas este año. Nada de vivir de las rentas... ;-)

**Comment by alexfernandez** [comment]
Pues no hemos visto ninguna por aquí en MadridJS... (hint, hint).

**Comment by dialelo** [comment]
La doy en español entonces, quedo pendiente de que concretemos la fecha.

**Comment by alexfernandez** [comment]
@dialelo, esta charla la vamos a planificar para el 28 de mayo. Necesito confirmación, ¿vale?

**Comment by dialelo** [comment]
Confirmado \o/

**Comment by alexfernandez** [comment]
Great :)
