### ISSUE TITLE
Taller de introducción práctica a Vue.js

### ISSUE THREAD

**Issue by rubnvp** [madridjs/talks#60]
# Title / Título
Introducción práctica a Vue.js

# Description / Descripción
Vue.js vende simplicidad y fácil adopción. Se autodefine como un “framework progresivo” porque lo podemos ir adaptando poco a poco y, según lo vayamos necesitando, estar seguros de que no nos fallará cuando nuestra aplicación crezca y sea mas compleja.

En esta taller Rubén Valseca tratará de mostrar cómo usar Vue con lo mínimo necesario y cómo de fácil es empezar a usarlo tirando código desde el minuto cero y con ejemplos prácticos. Aprovecharemos que detective Pikachu está en cines para hacer [esta pequeña pokedex](https://rubnvp.github.io/vue-pokedex/) y luego migraremos nuestra app a una aplicación más compleja con el vue-cli.

Este taller es introductorio, si ya has tocado Vue antes seguramente se te quede corto, puede serte útil si quieres “ver de qué va esto de Vue” y empezar a trastear un poco con el framework :)

Es requisito venir con un portátil con una versión de [Node.js](https://nodejs.org/es/) actualizada y un editor tipo [VS Code](https://code.visualstudio.com/). Partiremos de [este repositorio](https://github.com/rubnvp/vue-pokedex/) desde la rama `initial`.

# Speaker Bio / Bio del Ponente
Rubén trabaja como desarrollador Full-Stack en StyleSage, una empresa de Nueva York relacionada con el Big Data en el mundo de la moda. Enamorado de JavaScript, Vue.js y Python lleva años trabajando en el ecosistema startup. También organiza [VueJS Madrid](https://www.meetup.com/es-ES/VueJS-Madrid/), [Vue Spain](https://www.meetup.com/es-ES/Vuejs-Spain/) y el [FrontFest](https://frontfest.es/).

# Level / Nivel
Iniciación

# Duration / Duración
2 horas

# Constraints / Condicionantes
Sería perfecto hacerlo el 28 de Mayo en WildCodeSchool Madrid

**Comment by alexfernandez** [comment]
¡Todo gestionado, así da gusto! [Publicado](https://www.meetup.com/es-ES/madridjs/events/261494352/).

**Comment by alexfernandez** [comment]
[Hecho](https://www.meetup.com/es-ES/madridjs/events/261494352/).
