### ISSUE TITLE
Automatización y gestión de procesos con Runnerty

### ISSUE THREAD

**Issue by alo** [madridjs/talks#61]
# Title / Título
Automatización y gestión de procesos con Runnerty

# Description / Descripción
Tiempo y control. Como desarrolladores / devops, valoramos enormemente las herramientas que nos facilitan tener el control de nuestros procesos, ejecuciones y tareas planificadas.
Lamentablemente, no disponemos de muchas herramientas para lidiar con esto y las existentes son caras, rudimentarias o difícil de incorporar a nuestro stack de manera ágil.

Por esto vamos a hablar de Runnerty, un orquestador de procesos open source. Mostraremos cómo es posible solucionar problemas de planificación de procesos de una manera muy sencilla, con casos de uso reales.

# Speaker Bio / Bio del Ponente
Carlos Carmona - Desc corta: (Backend Lead en Coderty)
Más de 12 años como apasionado Backend y Web Developer.
Actualmente consultor de arquitectura de aplicaciones y optimización de procesos en Coderty (@CodertyStudio) y CTO de Runnerty (@runnerty_io)!

Álvaro Quirós twitter: @aloDev - Desc corta: (Frontend Lead en Coderty)
Front-end lead en @CodertyStudio, estandarte de @AngularAlmeria y maestro de ceremonias de @AlmeríaJS. Trabajo, constancia y cafeína conforman su ADN. Lleva al día a su equipo y los enrutadores de la nightly. El que está junto a Nela.

# Level / Nivel
Intermediate
(Beginner, Intermediate, Advanced)
(Iniciación, Intermedio, Avanzado)

# Duration / Duración
> 45 min
(30 min to one hour)
(30 minutos a una hora)

# Constraints / Condicionantes
Estamos en Madrid solo el día 27 de junio!
(Any constraints you have, e.g. specific dates)
(Condicionantes, por ejemplo una fecha específica)

**Comment by alo** [comment]
🙋‍♂️

**Comment by alexfernandez** [comment]
Movido a Node.js Madrid.
