### ISSUE TITLE
«Programando nuestra primera extensión multi-navegador en 40 minutos»

### ISSUE THREAD

**Issue by tripu** [madridjs/talks#63]
## Descripción

La [API *&laquo;Browser Extensions&raquo;* del W3C](https://browserext.github.io/browserext/) estandariza el desarrollo de *plug-ins*, *add-ons*, *extensiones* o *complementos* (llámese como se quiera) en la mayoría de los navegadores.
En esta charla vamos a explicar la estructura que tiene una extensión, qué archivos incluye, cómo se programa, y cómo se empaqueta para publicarla en los respectivos *markets*. Usaremos un caso simple como ejemplo para mostrar todo lo necesario; algo que los asistentes puedan luego reutilizar para programar sus propias extensiones.
Y probaremos nuestra extensión tanto [en Firefox](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions) como [en Chrom*](https://developer.chrome.com/extensions) para mostrar que el mismo código es válido en esos navegadores (y en otros, como Edge u Opera) con muy pocos cambios.

![image](https://user-images.githubusercontent.com/1016538/61271876-06ae3280-a7a6-11e9-9f02-b21ec9ef0517.png)

## Bio del ponente

Nacido en Madrid en 1980. Ingeniero en informática por la Universidad de Granada.
Durante los últimos 15 años ha trabajado como programador, analista, jefe de proyectos y CTO en organizaciones pequeñas; tanto en *start-ups* como en instituciones sin ánimo de lucro como en empresas multinacionales; en Sevilla, en Madrid, en Londres y en Tokio. Sus principales intereses son el *software* libre, GNU/Linux, los sistemas abiertos, la informática gráfica, interfaces y usabilidad, la tecnología de la web y JavaScript.
Hasta hace poco fue [programador web](https://www.w3.org/People/Alumni#antonio) dentro del [equipo de sistemas del W3C](https://www.w3.org/People/functions/systeam) durante cuatro años y medio.

## Nivel

**Intermedio**, porque al final se trata de programar en JS y de usar unas pocas APIs, pero no hay conceptos especialmente difíciles y la chicha de una extensión es bastante fácil de entender.

## Duración

**30&prime;&ndash;40&prime;**.

---

NB: la charla y la presentación podrían ser en español, o en inglés (lo que el grupo prefiera).

**Comment by javiervelezreyes** [comment]
Hola @tripu,

¿Te vendría bien dar la charla a finales de este mes?.

Intentaríamos que fuera el tercer jueves (24/11) tal y como es habitual pero podemos ajustarlo según tu agenda.

**Comment by tripu** [comment]
@javiervelezreyes:
En principio, un jueves por la tarde/noche, sin problema :+1:
El tercer jueves de este mes es 17 de octubre, y el del mes que viene, 21 de noviembre; ¿a cuál te refieres?

**Comment by javiervelezreyes** [comment]
Jeje,

Perdona, me referia al 24 de octubre no de noviembre. Ese día sería el
tercer jueves de mes ya que el 31 es también jueves.

Si te viene bien ese día lo dejamos así. Sino podríamos hacerlo el 17. Dime
y reservo sala ;)

**Comment by tripu** [comment]
@javiervelezreyes, confirmo para el 24 de octubre.
¿Sobre qué hora sería, y dónde?
¿Unos 40' de presentación + 10' para comentarios y preguntas está bien?
¿Qué relación de aspecto tendrá el proyector? ¿Conexión a inet?

**Comment by javiervelezreyes** [comment]
Los eventos los celebramos a las 19:00 y disponemos de una hora o sea que
perfecto. Recuerda que conviene estar media hora antes para montarlo todo.
Manu o yo procuraremos estar para echarte una mano en lo que necesites.

A falta de que me confirmen he reservado sitio en spotahome pero seguro que
no hay problema, sino te diría. Hay Internet lo que no se confirmarte es la
relación de aspecto del proyector pero supongo que será 16:9.

El sitio está en C/ Vizcaya, 12.

**Comment by tripu** [comment]
:+1:

**Comment by javiervelezreyes** [comment]
La comunidad es de habla española asi que mejor en español. No obstante lo dejamos en tus manos. Por cierto, no tengo tu nombre para incluirlo en el meetup. Cómo quieres llamarte :P

**Comment by tripu** [comment]
@javiervelezreyes, acabo de enviarte un e-mail :)
