### ISSUE TITLE
Creando y analizando una aplicación con Sveltejs

### ISSUE THREAD

**Issue by jesuscuesta** [madridjs/talks#64]
# Title / Título
Creando y analizando una aplicación con Sveltejs

# Description / Descripción
Actualmente cuando nos llega un proyecto frontend, la mayoría de las personas eligen entre Angular, React y/o Vuejs (siempre tendremos a alguien que vaya solo con jquery), pero parece que está tomado impulso una nueva alternativa, [Svelte](https://svelte.dev/).

¿Qué es Sveltejs? ¿Qué le hace diferente o mejor que a algunas de las opciones? ¿Quién está detrás de este framework? ¿Está suficiente maduro como para competir contra otras tecnologías?

Estos conceptos y algunos más los analizaremos en la charla, además de crear una aplicación con Svelte y analizarla y descubrir si tiene alguna ventaja para utilizarla.

# Speaker Bio / Bio del Ponente
Apasionado de las nuevas tecnologías, Líder Técnico del Centro de Expertos Javascript de AT Sistemas, Co-Organizador de los meetups Desarrolladores Cloud y Smart Devices, colaborador de OpenExpo Europe y Hackathon Lovers y aficionado a eventos tecnológicos, hackathones y marketing digital.

# Level / Nivel
Intermedio
Daremos por hecho que sabes:

- Que sabes Javascript (básico), HTML, CSS
- Qué es nodejs
- Qué es yarn
- Qué es una SPA

# Duration / Duración
45 minutos

Agenda:

19:00 - 19:05 - Presentación

19:05 - 19:45 - Creando y analizando una aplicación con Sveltejs - Jesús Cuesta

19:45 - 19:50 - Siguientes pasos - Jesús Cuesta

19:50 - 20:00 - Preguntas

20:00 - 21:00 - Cervezas, algo de picar y comentarios e impresiones.

# Constraints / Condicionantes

(Any constraints you have, e.g. specific dates)
(Condicionantes, por ejemplo una fecha específica)
Fecha: Para el 12, 13 o 14 de Noviembre.
Lugar y gastos: puedo conseguir que mi empresa consiga lugar, ponga picoteo y me deje tiempo para preparar mejor la charla, por las fechas anteriores.

**Comment by javiervelezreyes** [comment]
Hola Jesus,

Ya se que ya tenemos un meetup del tema y de hecho creo que esta charla la has publicado en tu meetup hace poco. No obstante, espero que esta respuesta no llegue tarde. Te apetece hablarnos de SvelteJS. Si quieres lo promocionamos como un evento conjunto y asi hablas de tu libro ;)

Te animas?
