### ISSUE TITLE
FastFlood: Historia de un memory leak masivo en el server

### ISSUE THREAD

**Issue by Serabe** [madridjs/talks#65]
# Title / Título

FastFlood: Historia de un memory leak masivo en el server

# Description / Descripción

¿Qué pasaría si tuvieses un memory leak tan gordo en tu servidor que la mayoría de los datos de tu request se quedase en memoria? ¿Y si además todo tu equipo estuviese en remoto y no hubiera dos personas en el mismo huso horario?

En esta charla repasamos algunas de las técnicas más típicas para encontrar fugas de memoria y algunas un poco más inusuales cuando tratamos con una fuga masiva.

También se incluyen ciertos consejos para organizar el trabajo cuando el equipo es remoto.

# Speaker Bio / Bio del Ponente

Ingeniero frontend en DockYard. Haciendo magia con y sin código.

# Level / Nivel

Se necesita un nível medio, al fin y al cabo estamos hablando de memory leaks, pero no debería ser necesario haberse enfrentado a ellos.

# Duration / Duración

30 - 40 minutos, aunque puedo detenerme más si la gente lo prefiere o lo necesita.

# Constraints / Condicionantes

* No puedo los martes por la tarde.
* Necesito saber el día y la hora con cierta antelación para pedir el tiempo en el trabajo.
* Aunque la charla trata sobre una fuga en FastBoot, el SSR de Ember, no es necesario conocer nada de este framework. Sólo tres slides se refieren específicamente a Ember y no es necesario conocer nada de este framework para entenderlas.

**Comment by javiervelezreyes** [comment]
Ey Sergio!,

Te toca arrancar el año. Así dejas el pabellón bien alto ;)
Te propongo moverlo todo para hacerlo el día 23, tercer jueves de mes, como tenemos por costumbre en el grupo.  Sería a las 19h en Spotahome (Calle de Vizcaya 12).

¿Te viene bien?

**Comment by Serabe** [comment]
Confirmo! 23 a las siete!

**Comment by javiervelezreyes** [comment]
Genial ;)


*Javier Vélez Reyes*Ph. D. Computer Science
javier.velez.reyes@gmail.com


*La cura para el aburrimiento es la curiosidad. *
*No hay cura para la curiosidad. **  Dorothy Parker. 1893 - 1967*

[LinkedIn - javiervelezreyes] <http://es.linkedin.com/in/javiervelezreyes/>
[Google+ - plus.google.com/+javiervelezreyes]
<http://gplus.to/javiervelezreyes>
[Youtube - youtube.com/c/javiervelezreyes]
<http://gplus.to/javiervelezreyes>
[Twitter - @javiervelezreye] <https://twitter.com/javiervelezreye>

**Comment by Serabe** [comment]
¡Cerrando el issue!
