### ISSUE TITLE
TESTABLE - A GAMIFIED TOOL TO TEACH UNIT TESTS IN JAVASCRIPT - Talk in English

### ISSUE THREAD

**Issue by marabesi** [madridjs/talks#67]
# Title / Título
TESTABLE - GAMIFIED TOOL TO TEACH UNIT TESTS IN JAVASCRIPT (Talk in English)

# Description / Descripción

Testing has always been a subject of attention. Nowadays modern libraries come with their own test suite, usually a unit test suite. Therefore, enterprise developers and students might have the perception that testing is a boring task.

Testable, is a web-based application built with reactjs to teach unit test teaching for professional developers and students that uses gamification as a teaching strategy approach.

In this scenario, the talk presents the challenges faced during the development phase such as:

- Why javascript in the first place?
- Understanding javascript code with AST
- Front end patterns used
- Tracking system and animations
 
As well as the gamification part of it, should we use gamification an alternative strategy?

# Speaker Bio / Bio del Ponente

Marabesi is addicted to software development, best practices, design patterns and testable code.

# Level / Nivel

(Beginner/Intermediate)

# Duration / Duración

40 min to one hour

# Constraints / Condicionantes

N/A

**Comment by javiervelezreyes** [comment]
Hi Marabesi, 

February is for you! We meet the 3rd Thursday of each month. Therefore, in this case, the selected date is February 20, at 7pm. Is this date good for you?

**Comment by marabesi** [comment]
sounds good to me : D

**Comment by javiervelezreyes** [comment]
Great, Im preparing it
