### ISSUE TITLE
Bye Bye Nativo, welcome a la Web del futuro

### ISSUE THREAD

**Issue by agonsant** [madridjs/talks#68]
# Title / Título

Bye Bye Nativo, welcome a la Web del futuro

# Description / Descripción

> Año 202X, la web ha tomado el control de todas las plataformas de desarrollo. Ya casi no quedan aplicaciones Nativas y todas las plataformas se mueven utilizando JavaScript...

Este es posiblemente el relato que podremos leer en un futuro no muy lejano. 

En esta charla se mostrarán las Web Capabilities y su integración dentro de una Progressive Web App, indagando en ejemplos y viendo el código para poder invocar a las nuevas API's JavaScript que se están implementando.

- Web Share and Web Share Target API

- Badging API

- Contact Picker API

- File System API 

- Web Bluetooth API

- Web Authentication API

- ... y muchas más.

# Speaker Bio / Bio del Ponente

Ingeniero de Software, me encanta la algoritmia, las estructuras de datos y el performance. Jamming with code.

# Level / Nivel

**Intermedio**. Vamos a hablar de API's experimentales o en Draft, aunque no pretendo enseñar mucho código, si que veremos algunos ejemplos de invocación a las API's.

# Duration / Duración

Una hora, aunque podría extenderme más y la materia tiene bastante que enseñar. 

# Constraints / Condicionantes

- Me gustaría dar la charla a partir del 1 Marzo. (No podría del 19-24 de Marzo que estoy de viaje)

**Comment by javiervelezreyes** [comment]
Hola @agonsant,

Que te parece mover la charla para el Jueves 16 de Marzo?

Te va bien?

**Comment by agonsant** [comment]
Buenas,
Entiendo que te refieres al Jueves 16 de Abril? O sería el Lunes 16 de Marzo?
Muchas gracias

**Comment by javiervelezreyes** [comment]
Va sumale 10 y dejalo en marzo jeje. 26 de marzo disculpa ;)

**Comment by agonsant** [comment]
Jejeje perfecto entonces pues solo me faltaría saber hora y lugar 😜

**Comment by javiervelezreyes** [comment]
Sería a las 19h. Voy gestionando el lugar 😋

**Comment by javiervelezreyes** [comment]
Alex,

Pf, escribeme por correo a javier.velez.reyes@gmail.com
