### ISSUE TITLE
Hitting the Couch

### ISSUE THREAD

**Issue by ukmadlz** [madridjs/talks#7]
Description:
No matter where you look in technology, everything has an online component. But with the advancement of web technologies and mobile apps, offline is becoming a key characteristic. This talk is a whistle stop tour on taking advantage of replication to achieve harmony between your application and your datalayer.

Be prepared for live code and theory on using CouchDB with libraries to work inside your apps.

Bio:
Mike spends his days as Developer Advocate at [IBM Cloudant](http://cloudant.com), using his time to share knowledge on rapid development and CouchDB. Most of the time he can be found in the middle of a prototype in some combination of JavaScript, server tech and odd API's.

Mike also happens to be an active part of the hacker subculture, taking part in hackathons and development conferences.

**Comment by alexfernandez** [comment]
Sounds interesting. If we can pass it as an entry-level talk (which we are severely lacking) we might do it in May, is that OK with you? I assume you have to come to Madrid from the UK for the talk.

**Comment by ukmadlz** [comment]
Yeah, that's fine.

Yeah, I'd come over from the UK.

**Comment by alexfernandez** [comment]
That's great! I have added it to the May calendar. Usually we set the date at the beginning of the month, but in this case we might try to close it beforehand if you need more time in advance to buy plane tickets or accomodate you in any way, given that you have to travel: just let us know.

Otherwise we will contact you in the first week of May to close the date, which is usually the last Thursday of the month, thus the 28th.

**Comment by ukmadlz** [comment]
@alexfernandez when would you be able to confirm the dates for the May meetup? I've got to arrange meeting's in Madrid and possibly Barcelona, and I'd like to confirm everything in March/April.

**Comment by alexfernandez** [comment]
I'll try to do it this week, feel free to ping me next week.

**Comment by ukmadlz** [comment]
@alexfernandez have you got the dates for the May meetup yet?

**Comment by alexfernandez** [comment]
I am aiming for Thursday May 28th, I have copied you in the mail request to our friends at Impact Hub.
