### ISSUE TITLE
Como desarrollar un Frontend en una arquitectura de Microservicios

### ISSUE THREAD

**Issue by kevinccbsg** [madridjs/talks#71]
# Title / Título

Como desarrollar un Frontend en una arquitectura de Microservicios

# Description / Descripción

Trabajar en una arquitectura de microservicios es un reto que podemos encontrar en muchas de nuestras empresas. Aunque cada microservicio en sí es independiente y podemos trabajar con el de manera aislada, a veces, nos encontramos con que el desarrollo del Frontend no siempre está tan aislado, por lo que tenemos que crear entornos de desarrollo complejos para trabajar de manera local. Esto en muchos casos puede suponer un proceso complicado para los desarrolladores frontend o para el onBoarding de nuevos compañeros.

En esta charla, os compartiré mi experiencia de como desarrollamos una de nuestras aplicaciones en una arquitectura de microservicios, resolviendo estos problemas y consiguiendo que la parte frontend pueda centrarse en lo que mejor sabe hacer, crear experiencias de usuario increíbles.

# Speaker Bio / Bio del Ponente

Javascript Developer en Guidesmiths, apasionado de las tecnologías Web y la formación constante. Actualmente me dedico con tecnologías como Node.js, React, Docker, MongoDB y Cypress creando Microservicios y aplicaciones para empresas de Holanda y Suecia. También imparto formación de Javascript para distintas empresas.

# Level / Nivel

Intermedio

# Duration / Duración

45 minutos

# Constraints / Condicionantes

Algunas semanas lunes, martes y jueves no puedo pero dependería de la fecha. Por todo lo demás sin problemas.

**Comment by javiervelezreyes** [comment]
Ey Kevin,

Llego tu turno. Se que estamos en confinamiento y el evento tendría que ser en remoto en modo webminar. En la organización somos conscientes de que este formato puede ser más incómodo para el ponente así que la decisión final es tuya. Pero en la última ocasión tuvimos éxito de aforo y crítica 😉

Si te ánimas intentaríamos programar el evento para el uno de los próximos jueves del mes día 23 o el 30. Si te viene mal podemos buscar otro día.

Por favor dame una respuesta cuanto antes para poder gestionarlo.

Un e-brazo Javi 😋

**Comment by kevinccbsg** [comment]
Hola @javiervelezreyes,

Perdona no te escribí antes. Estaría disponible y encantado de poder participar. El formato online no es un problema, estoy bastante acostumbrado ya.

Tanto el 23 como el 30 me van bien. 😃

Un saludo.

**Comment by javiervelezreyes** [comment]
Perfecto Kevin, déjame que coordine y mañana público el evento en meetup 😉

**Comment by javiervelezreyes** [comment]
Hola Kevin,

Acabo de publicar tu evento. Para coordinarnos a partir de ahora y proceder con la retransmisión online por favor escribeme a javier.velez.reyes@gmail.com. 

Te espero, un saludo.

**Comment by kevinccbsg** [comment]
Muchas gracias por el espacio para contar mi charla. Yo creo que podemos cerrar el issue 👍
