### ISSUE TITLE
Charla: Desarrollando aplicaciones SEO friendly y escalables con NextJS, desplegando en Vercel

### ISSUE THREAD

**Issue by rafinskipg** [madridjs/talks#72]
# Title / Título

Desarrollo de aplicaciones JAMStack, SEO friendly y escalables con NextJS. 

# Description / Descripción

Veremos las funcionalidades core de nextjs y desarrollaremos en vivo una aplicación con las siguientes funcionalidades:
- SSR (server side rendering)
- SSG (static site generation) 
- Desplegaremos en funciones serverles + CDN utilizando Vercel.
- Explicaremos como desplegar una instancia en google app engine
- Veremos como organizar el código en una aplicación next de forma óptima

# Speaker Bio / Bio del Ponente

Rafael Ventura, desarrollador fullstack y cofundador de Etéreo, una agencia de software en Madrid. Durante sus más de diez años de experiencia haciendo aplicaciones web Rafael ha trabajado con la mayoría de frameworks javascript y ahora desarrolla codo con codo con sus compañeros de Etéreo soluciones para otras empresas.

# Level / Nivel

Intermedio

(Beginner, Intermediate, Advanced)
(Iniciación, Intermedio, Avanzado)

# Duration / Duración

1h 

(30 min to one hour)
(30 minutos a una hora)

# Constraints / Condicionantes

Sólo online. 

(Any constraints you have, e.g. specific dates)
(Condicionantes, por ejemplo una fecha específica)

**Comment by javiervelezreyes** [comment]
Hola Rafa!

Que tal el verano. Te apetece estrenar el nuevo curso en MadridJS con tu charla? Como ya sabes por el covid tendriamos que hacerlo en remoto. Solemos hacer las charlas un Jueves a final de mes asi que una buena fecha tentativa seria el próximo dia 24/09/2020. Aunque si quieres moverlo a otro día no habría demasiado problema. Nosotros nos adaptamos.

Me escribes a javier.velez.reyes@gmail.com y ultimamos detalles? 

Gracias tio! Un abrazo ;)
