### ISSUE TITLE
La tele en la web: MSNBC

### ISSUE THREAD

**Issue by juampy72** [madridjs/talks#8]
[MSNBC](http://www.msnbc.com) es un canal estadounidense de noticias. [AngularJS](https://angularjs.org) juega un papel fundamental tanto en la experiencia del desarrollador como del usuario final. En esta charla veremos cómo se ha utilizado satisfactoriamente en algunos de sus retos.

Durante más de dos años, [Lullabot](https://www.lullabot.com) ha trabajado codo con codo con la MSNBC en migrar y rehacer su portal de noticias. Uno de los requisitos iniciales era que tanto la cabecera como el pie de la web debían poder ser embebidos en otras webs. Decidimos emplear directivas de AngularJS para este requisito y con ello pusimos la semilla que originó una larga lista de implementaciones que desarrollamos con este framework. De entre ellas destacan el retransmitir eventos en vivo, integrar el canal de televisión dentro de la web o ofrecer pseudo-SPAs para ciertas secciones.

Soy [Juampy](http://about.me/juampy) (Juan Pablo), programador back end en [Lullabot](https://www.lullabot.com), una empresa distribuida de estrategia, diseño y desarrollo. Participo activamente en la comunidad de Drupal tanto en [módulos como en el core](https://www.drupal.org/u/juampy) y he escrito dos [libros sobre Drush](http://bit.ly/1AxZFtx), la interfaz de línea de comandos para Drupal. Desde que empecé en la MSNBC me he metido más y más en JavaScript, disfrutanto la experiencia y escribiendo [artículos](https://www.lullabot.com/blog/article/processing-forms-angularjs) sobre cómo hacemos las cosas.

*Nota: puedo hacer esta charla en inglés si la organización lo prefiere.*

**Comment by alexfernandez** [comment]
Parece interesante. Lo único es que, ¿no hay un poco de overlap con AngularJS Madrid? ¿Es algo de JavaScript aparte de Angular, o no? ¿Cómo lo ves?

**Comment by juampy72** [comment]
Tienes razón. En la charla todo el JavaScript que comentaré será AngularJS y cómo se integra con Drupal. ¿Propongo esta charla en http://www.meetup.com/AngularJS_Madrid?

**Comment by alexfernandez** [comment]
Por nosotros encantados de tenerla siempre que esté relacionada con JavaScript. Podemos hacer una cosa: proponla allí, y si no te la aceptaran (que seguro que sí), volvemos a hablar, ¿vale?

**Comment by juampy72** [comment]
OK!
