### ISSUE TITLE
Drag&drop con backbone crossbrowser. Soportando navegadores legacy con jQueryUi.

### ISSUE THREAD

**Issue by manolomaldonado** [madridjs/talks#9]
Pese a que parece que html5 poco a poco se va consolidando en la mayoría de proyectos que se desarrollan en la actualidad y es cada vez menos habitual encontrar proyectos que necesiten funcionar en navegadores con versiones que no soporten html5 como navegador corporativo, hay veces que no hay más remedio que adaptarse a los requerimientos de los clientes que todavía utilizan el, a falta de una palabra menos adecuada, 'poco amable' ie8. 

Mostraremos una posible solución usando la librería backbone.js con jQueryUi en las vistas, con una aplicación real de reserva de vuelos sustituyendo las cualidades nativas de html5 para soportar navegadores legacy.

David Rielo, es desarrollador respondable de frontend en Lextrend (http://www.lextrend.com) donde trabaja principalmente con Backbone, Node y Gulp. Comenzó el lado servidor con Java en sus inicios pero rapidaménte se vió atraido por el desarrollo del lado cliente y por las posibilidades de javascript donde descubrió su verdadera vocación.

**Comment by alexfernandez** [comment]
Esta charla tiene pinta de ser avanzada, ¿no?

**Comment by manolomaldonado** [comment]
Hola Alex, el concepto puede sonar "avanzado" pero le daríamos un enfoque práctico en el que  se mostrará como manipular el DOM, asequible para todas las audiencias con unos conocimientos mínimos de JS y JQuery.

**Comment by alexfernandez** [comment]
Pues perfecto, porque andamos escasos de charlas de iniciación. Os apunto en principio para [junio](https://github.com/madridjs/talks/blob/master/README.md), si os parece.

**Comment by manolomaldonado** [comment]
Por nuestra parte, perfecto para junio.

**Comment by alexfernandez** [comment]
Auténtico atraco a mano armada: ¿podríais hacer la charla el jueves 30 de abril? Please, respondedme a alexfernandeznpm@gmail.com.

**Comment by alexfernandez** [comment]
Ya estamos en septiembre y es hora de programar la charla de este mes. ¿El jueves 24 os viene bien?

**Comment by alexfernandez** [comment]
Necesito una respuesta cuanto antes para planificar el evento, ¿os viene bien el jueves 24 de este mes?

**Comment by manolomaldonado** [comment]
Hola Alex, acabo de aterrizar de vacaciones(literalmente, estoy en el aeropuerto). Te contacto a lo largo del día.

Un saludo

**Comment by alexfernandez** [comment]
¿Qué me dices del evento?

**Comment by alexfernandez** [comment]
Buenas, volvemos a la carga después de las vacaciones. ¿Estarías disponible para dar esta charla en marzo?

**Comment by manolomaldonado** [comment]
Hola Alex, te confirmo mañana mismo.

Un saludi
